# Code generated by gotypegen. DO NOT EDIT.

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel
from datetime import datetime


##########
# source: models.go

StringEncodedMap = Dict[str, Any]

# LLMOutput is the output envelope from an LLM provider task.
# This is the contract between chat apps (sdk-py) and the agent runtime (go/api).
class LLMOutput(BaseModel):
    response: str = ""
    reasoning: Optional[str] = None
    tool_calls: Optional[List[ToolCall]] = None
    usage: Optional[LLMUsage] = None

# LLMInput is the input envelope for an LLM provider task.
class LLMInput(BaseModel):
    model: Optional[str] = None
    context_size: int = 0
    temperature: Optional[float] = None
    top_p: Optional[float] = None
    top_k: Optional[int] = None
    min_p: Optional[float] = None
    frequency_penalty: Optional[float] = None
    presence_penalty: Optional[float] = None
    repetition_penalty: Optional[float] = None
    seed: Optional[int] = None
    stop: List[str]
    max_tokens: Optional[int] = None
    reasoning_effort: Optional[str] = None
    reasoning_max_tokens: Optional[int] = None
    system_prompt: str = ""
    context: List[LLMContextMessage]
    role: ChatMessageRole
    text: Optional[str] = None
    reasoning: Optional[str] = None
    attachments: Optional[List[FileRef]] = None
    images: Optional[List[str]] = None
    files: Optional[List[str]] = None
    tools: Optional[List[Tool]] = None
    tool_call_id: Optional[str] = None

# LLMContextMessage represents a message in the chat context for LLM tasks
class LLMContextMessage(BaseModel):
    role: ChatMessageRole
    text: Optional[str] = None
    reasoning: Optional[str] = None
    images: Optional[List[str]] = None
    files: Optional[List[str]] = None
    tools: Optional[List[Tool]] = None
    tool_calls: Optional[List[ToolCall]] = None
    tool_call_id: Optional[str] = None

# ToolCall represents a tool call from an LLM response (wire format)
# This is a transport object for parsing LLM responses, not a database model
class ToolCall(BaseModel):
    id: str = ""
    type: ToolCallType
    function: ToolCallFunction

# ToolCallFunction contains the function name and arguments from an LLM tool call
class ToolCallFunction(BaseModel):
    name: str = ""
    arguments: StringEncodedMap

# LLMUsage contains token usage and performance metrics from an LLM response
class LLMUsage(BaseModel):
    stop_reason: str = ""
    time_to_first_token: float = 0.0
    tokens_per_second: float = 0.0
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    reasoning_tokens: int = 0
    reasoning_time: float = 0.0

# FileRef is a lightweight reference to a file with essential metadata.
# Used in chat inputs/context instead of full File objects.
class FileRef(BaseModel):
    id: str = ""
    uri: str = ""
    filename: str = ""
    content_type: str = ""
    size: int = 0

# Tool represents a tool definition for LLM function calling
class Tool(BaseModel):
    type: ToolCallType
    function: ToolFunction

class ToolFunction(BaseModel):
    name: str = ""
    description: str = ""
    parameters: ToolParameters
    required: Optional[List[str]] = None

class ToolParameters(BaseModel):
    type: ToolParamType
    title: str = ""
    properties: ToolParameterProperties
    required: Optional[List[str]] = None

ToolParameterProperties = Dict[str, "ToolParameterProperty"]

class ToolParameterProperty(BaseModel):
    type: ToolParamType
    title: str = ""
    description: str = ""
    properties: Optional[ToolParameterProperties] = None
    items: Optional[ToolParameterProperty] = None
    required: Optional[List[str]] = None

class ChatMessageRole(str, Enum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"

# Tool call types
class ToolCallType(str, Enum):
    TOOL_TYPE_FUNCTION = "function"

# Tool parameter types
class ToolParamType(str, Enum):
    OBJECT = "object"
    STRING = "string"
    INTEGER = "integer"
    NUMBER = "number"
    BOOLEAN = "boolean"
    ARRAY = "array"
    NULL = "null"


# Resolve forward references
LLMOutput.model_rebuild()
LLMInput.model_rebuild()
LLMContextMessage.model_rebuild()
ToolCall.model_rebuild()
ToolCallFunction.model_rebuild()
LLMUsage.model_rebuild()
FileRef.model_rebuild()
Tool.model_rebuild()
ToolFunction.model_rebuild()
ToolParameters.model_rebuild()
ToolParameterProperty.model_rebuild()

