# Code generated by gotypegen. DO NOT EDIT.

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel
from datetime import datetime


##########
# source: models.go

# DecisionChoiceOption is one answer option of a choice question.
class DecisionChoiceOption(BaseModel):
    # Name is returned as the choice and keys the probabilities.
    name: str = ""
    # Description says what the option covers.
    description: Optional[Any] = None

# DecisionChoiceQuestion asks which one of a fixed set of options holds.
class DecisionChoiceQuestion(BaseModel):
    # ID is the caller's key for the question; its answer comes back under it.
    id: str = ""
    instructions: Any
    options: List[DecisionChoiceOption]

# DecisionScoreQuestion asks where the state sits on ordered levels.
class DecisionScoreQuestion(BaseModel):
    id: str = ""
    instructions: Any
    # Levels are described low end to high end; a level's number is its index.
    levels: List[Any]

# DecisionNoulCriteria pins down what yes and no mean for a noul question.
class DecisionNoulCriteria(BaseModel):
    true: Optional[Any] = None
    false: Optional[Any] = None

# DecisionNoulQuestion asks for the probability that something is true.
class DecisionNoulQuestion(BaseModel):
    id: str = ""
    instructions: Any
    criteria: Optional[DecisionNoulCriteria] = None

# DecisionInput is one state and the questions asked of it.
class DecisionInput(BaseModel):
    state: Any
    choices: Optional[List[DecisionChoiceQuestion]] = None
    scores: Optional[List[DecisionScoreQuestion]] = None
    nouls: Optional[List[DecisionNoulQuestion]] = None

# DecisionChoiceAnswer is the answer to a choice question.
class DecisionChoiceAnswer(BaseModel):
    # Choice is the highest-probability option.
    choice: str = ""
    confidence: float = 0.0
    # Probabilities maps every option name to its probability.
    probabilities: Dict[str, float]

# DecisionScoreAnswer is the answer to a score question.
class DecisionScoreAnswer(BaseModel):
    # Score is the probability-weighted level, 0 to the top level number.
    score: float = 0.0
    # Normalized is Score over the top level number: 0 to 1.
    normalized: float = 0.0
    confidence: float = 0.0
    # Probabilities maps each level number, as a string, to its probability.
    probabilities: Dict[str, float]
    # Legend maps each level number back to its description.
    legend: Dict[str, Any]

# DecisionNoulAnswer is the answer to a noul question.
class DecisionNoulAnswer(BaseModel):
    # Noul is the probability that the answer is yes.
    noul: float = 0.0

# DecisionOutput is the answers, keyed by question id within each kind.
class DecisionOutput(BaseModel):
    choices: Dict[str, DecisionChoiceAnswer]
    scores: Dict[str, DecisionScoreAnswer]
    nouls: Dict[str, DecisionNoulAnswer]
    # Model is the model that answered.
    model: str = ""
    # InputTokens is what the model read; decision models write none.
    input_tokens: int = 0

# StreamDelta is the marker base for all streaming delta types.
# Types embedding StreamDelta are routed through the delta channel.
class StreamDelta(BaseModel):
    pass

# LLMOutput is the output envelope from an LLM provider task.
# This is the contract between chat apps (sdk-py) and the agent runtime (go/api).
class LLMOutput(BaseModel):
    response: str = ""
    reasoning: Optional[str] = None
    tool_calls: Optional[List[ToolCall]] = None
    usage: Optional[LLMUsage] = None

# ToolCallDelta is an incremental update to a tool call, identified by index.
# First delta for an index carries ID, Type, and Function.Name.
# Subsequent deltas carry only Function.Arguments fragments.
class ToolCallDelta(BaseModel):
    index: int = 0
    id: Optional[str] = None
    type: Optional[ToolCallType] = None
    function: Optional[ToolCallFunctionDelta] = None

    _field_tags: ClassVar[dict] = {
        "id": {"merge": "replace"},
        "type": {"merge": "replace"},
        "function": {"merge": "nested"},
    }

# ToolCallFunctionDelta carries partial tool call function data.
# Arguments is a raw JSON string fragment — concatenate by index, parse on completion.
class ToolCallFunctionDelta(BaseModel):
    name: str = ""
    arguments: str = ""

    _field_tags: ClassVar[dict] = {
        "name": {"merge": "replace"},
        "arguments": {"merge": "concat"},
    }

# ToolChoice constrains tool calling for a turn. Providers spell this
# differently (OpenAI tool_choice, Anthropic tool_choice.type any/tool,
# Gemini functionCallingConfig); apps translate at the provider boundary.
class ToolChoice(BaseModel):
    mode: ToolChoiceMode
    name: Optional[str] = None

# ResponseFormat constrains the shape of the model's response.
# JSONSchema is required when Type is json_schema.
class ResponseFormat(BaseModel):
    type: ResponseFormatType
    name: Optional[str] = None
    json_schema: Optional[Any] = None
    strict: Optional[bool] = None

# LLMSettings is everything that configures a generation independent of the
# conversation: context, sampling, system prompt, tools and output
# constraints. Embedded (tstype extends) by BaseLLMInput — an agent's stored
# configuration — and LLMInput — a single call — so a field added here
# reaches both, and the call is built from the configuration by one
# assignment.
# 
# Which model runs is not a setting: the app is the model. An app that
# fronts several models (a router) declares its own `model` input.
class LLMSettings(BaseModel):
    context_size: int = 0
    temperature: Optional[float] = None
    top_p: Optional[float] = None
    top_k: Optional[int] = None
    min_p: Optional[float] = None
    frequency_penalty: Optional[float] = None
    presence_penalty: Optional[float] = None
    repetition_penalty: Optional[float] = None
    seed: Optional[int] = None
    stop: Optional[List[str]] = None
    max_tokens: Optional[int] = None
    reasoning_effort: Optional[str] = None
    reasoning_max_tokens: Optional[int] = None
    system_prompt: str = ""
    tools: Optional[List[Tool]] = None
    tool_choice: Optional[ToolChoice] = None
    response_format: Optional[ResponseFormat] = None

# LLMContextMessage represents a message in the chat context for LLM tasks
class LLMContextMessage(BaseModel):
    role: ChatMessageRole
    text: Optional[str] = None
    reasoning: Optional[str] = None
    images: Optional[List[str]] = None
    files: Optional[List[str]] = None
    tools: Optional[List[Tool]] = None
    tool_calls: Optional[List[ToolCall]] = None
    tool_call_id: Optional[str] = None

# DeltaEvent is the generic streaming envelope on the NDJSON wire.
# Delta is raw bytes — consumers parse based on context.
# 
# It is deliberately not LLM-specific: agent lifecycle events and any future
# delta producer share this envelope, which is why the identity field below is
# a bare resource id rather than anything named after chat.
class DeltaEvent(BaseModel):
    delta: Any
    seq: int = 0
    # ResourceID names what this delta belongs to — for an LLM task, the
    # assistant chat message being generated.
    # 
    # Without it a consumer can only assume deltas belong to whatever it is
    # currently building, which breaks the moment a message carries no text
    # (a tool-call-only turn) and the previous message's state is still live.
    # 
    # The producer copies this from the graph and never interprets it: ids come
    # from one idgen space, so a consumer matches against the ids it already
    # tracks and buffers anything it does not recognise yet. A resource_type
    # companion is deliberately absent — nothing needs to route before matching.
    # Empty when the task has no execution edge (a plain app run).
    resource_id: str = ""
    # End, when set, carries no delta: it is the id of the task or agent run
    # whose deltas on this key are complete. It follows the last of them on
    # the same key, so an in-process follower reads to it instead of guessing
    # when the stream is over. The stream layer never sends it to clients.
    end: str = ""

StringEncodedMap = Dict[str, Any]

# ToolCall represents a tool call from an LLM response (wire format)
# This is a transport object for parsing LLM responses, not a database model
class ToolCall(BaseModel):
    id: str = ""
    type: ToolCallType
    function: ToolCallFunction

# ToolCallFunction contains the function name and arguments from an LLM tool call
class ToolCallFunction(BaseModel):
    name: str = ""
    arguments: StringEncodedMap

# LLMUsage contains token usage and performance metrics from an LLM response
class LLMUsage(BaseModel):
    stop_reason: str = ""
    time_to_first_token: float = 0.0
    tokens_per_second: float = 0.0
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    reasoning_tokens: int = 0
    reasoning_time: float = 0.0

# FileRef is a lightweight reference to a file with essential metadata.
# Used in chat inputs/context instead of full File objects.
class FileRef(BaseModel):
    id: str = ""
    uri: str = ""
    filename: str = ""
    content_type: str = ""
    size: int = 0

# Tool represents a tool definition for LLM function calling
class Tool(BaseModel):
    type: ToolCallType
    function: ToolFunction

class ToolFunction(BaseModel):
    name: str = ""
    description: str = ""
    parameters: ToolParameters
    required: Optional[List[str]] = None

class ToolParameters(BaseModel):
    type: ToolParamType
    title: str = ""
    properties: Optional[ToolParameterProperties] = None
    required: Optional[List[str]] = None

ToolParameterProperties = Dict[str, "ToolParameterProperty"]

class ToolParameterProperty(BaseModel):
    # Type is the JSON Schema type of the value. Empty when AnyOf is set: the
    # value then has one of several shapes, and naming a single type would be
    # telling the model something untrue about what it may send.
    type: Optional[ToolParamType] = None
    # AnyOf lists the shapes a value may take, each described as a property of
    # its own. Anthropic and OpenAI both accept anyOf in tool schemas. Before
    # this field existed the converter picked one branch and dropped the rest,
    # so an app that accepted "401" or 401 could only tell the model about one.
    anyOf: Optional[List[ToolParameterProperty]] = None
    # Enum is the closed set of values a scalar may take, kept as data so a
    # consumer choosing arguments does not have to parse it back out of the
    # description.
    enum: Optional[List[Any]] = None
    title: str = ""
    description: str = ""
    properties: Optional[ToolParameterProperties] = None
    items: Optional[ToolParameterProperty] = None
    required: Optional[List[str]] = None

# DecisionVisionInput is the input of a decision model that also sees
# images: a DecisionInput plus the images the questions are about.
class DecisionVisionInput(DecisionInput, BaseModel):
    # Images are file URIs. Every question sees them.
    images: Optional[List[str]] = None

# LLMDelta is a streaming delta for LLMOutput.
class LLMDelta(StreamDelta, BaseModel):
    response: str = ""
    reasoning: Optional[str] = None
    tool_calls: Optional[List[ToolCallDelta]] = None
    usage: Optional[LLMUsage] = None

    _field_tags: ClassVar[dict] = {
        "response": {"merge": "concat"},
        "reasoning": {"merge": "concat"},
        "tool_calls": {"merge": "indexed"},
        "usage": {"merge": "replace"},
    }

# LLMInput is the input envelope for an LLM provider task: the settings plus
# the conversation, with the current turn split out of the context.
class LLMInput(LLMSettings, BaseModel):
    context: List[LLMContextMessage]
    role: Optional[ChatMessageRole] = None
    text: Optional[str] = None
    reasoning: Optional[str] = None
    attachments: Optional[List[FileRef]] = None
    images: Optional[List[str]] = None
    files: Optional[List[str]] = None
    tool_call_id: Optional[str] = None

class ChatMessageRole(str, Enum):
    # LLM wire-protocol roles
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"
    # Internal bookkeeping roles — never sent to the LLM provider.
    # BuildContext folds injections into the user turn and replaces
    # compaction markers with their summary. Event messages are display-only
    # system info (a hook ran, ...) and BuildContext skips them.
    INJECTION = "injection"
    COMPACTION = "compaction"
    EVENT = "event"

class MergeStrategy(str, Enum):
    CONCAT = "concat"
    REPLACE = "replace"
    INDEXED = "indexed"
    NESTED = "nested"

class ToolChoiceMode(str, Enum):
    NONE = "none"
    AUTO = "auto"
    REQUIRED = "required"
    FUNCTION = "function"

class ResponseFormatType(str, Enum):
    TEXT = "text"
    JSON_OBJECT = "json_object"
    JSON_SCHEMA = "json_schema"

# Tool call types
class ToolCallType(str, Enum):
    TOOL_TYPE_FUNCTION = "function"

# Tool parameter types
class ToolParamType(str, Enum):
    OBJECT = "object"
    STRING = "string"
    INTEGER = "integer"
    NUMBER = "number"
    BOOLEAN = "boolean"
    ARRAY = "array"
    NULL = "null"


# Resolve forward references
DecisionChoiceOption.model_rebuild()
DecisionChoiceQuestion.model_rebuild()
DecisionScoreQuestion.model_rebuild()
DecisionNoulCriteria.model_rebuild()
DecisionNoulQuestion.model_rebuild()
DecisionInput.model_rebuild()
DecisionChoiceAnswer.model_rebuild()
DecisionScoreAnswer.model_rebuild()
DecisionNoulAnswer.model_rebuild()
DecisionOutput.model_rebuild()
StreamDelta.model_rebuild()
LLMOutput.model_rebuild()
ToolCallDelta.model_rebuild()
ToolCallFunctionDelta.model_rebuild()
ToolChoice.model_rebuild()
ResponseFormat.model_rebuild()
LLMSettings.model_rebuild()
LLMContextMessage.model_rebuild()
DeltaEvent.model_rebuild()
ToolCall.model_rebuild()
ToolCallFunction.model_rebuild()
LLMUsage.model_rebuild()
FileRef.model_rebuild()
Tool.model_rebuild()
ToolFunction.model_rebuild()
ToolParameters.model_rebuild()
ToolParameterProperty.model_rebuild()
DecisionVisionInput.model_rebuild()
LLMDelta.model_rebuild()
LLMInput.model_rebuild()

