# Code generated by gotypegen. DO NOT EDIT.

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Any, Dict, List, Optional, TypedDict, Union
from datetime import datetime


##########
# source: models.go

StringEncodedMap = Dict[str, Any]

# LLMOutput is the output envelope from an LLM provider task.
# This is the contract between chat apps (sdk-py) and the agent runtime (go/api).
class LLMOutput(TypedDict, total=False):
    response: str
    reasoning: Optional[str]
    tool_calls: Optional[List[ToolCall]]
    usage: Optional[LLMUsage]

# LLMInput is the input envelope for an LLM provider task.
class LLMInput(TypedDict, total=False):
    model: Optional[str]
    context_size: int
    temperature: Optional[float]
    top_p: Optional[float]
    top_k: Optional[int]
    min_p: Optional[float]
    frequency_penalty: Optional[float]
    presence_penalty: Optional[float]
    repetition_penalty: Optional[float]
    seed: Optional[int]
    stop: List[str]
    max_tokens: Optional[int]
    reasoning_effort: Optional[str]
    reasoning_max_tokens: Optional[int]
    system_prompt: str
    context: List[LLMContextMessage]
    role: ChatMessageRole
    text: Optional[str]
    reasoning: Optional[str]
    attachments: Optional[List[FileRef]]
    images: Optional[List[str]]
    files: Optional[List[str]]
    tools: Optional[List[Tool]]
    tool_call_id: Optional[str]

# LLMContextMessage represents a message in the chat context for LLM tasks
class LLMContextMessage(TypedDict, total=False):
    role: ChatMessageRole
    text: Optional[str]
    reasoning: Optional[str]
    images: Optional[List[str]]
    files: Optional[List[str]]
    tools: Optional[List[Tool]]
    tool_calls: Optional[List[ToolCall]]
    tool_call_id: Optional[str]

# ToolCall represents a tool call from an LLM response (wire format)
# This is a transport object for parsing LLM responses, not a database model
class ToolCall(TypedDict, total=False):
    id: str
    type: ToolCallType
    function: ToolCallFunction

# ToolCallFunction contains the function name and arguments from an LLM tool call
class ToolCallFunction(TypedDict, total=False):
    name: str
    arguments: StringEncodedMap

# LLMUsage contains token usage and performance metrics from an LLM response
class LLMUsage(TypedDict, total=False):
    stop_reason: str
    time_to_first_token: float
    tokens_per_second: float
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    reasoning_tokens: int
    reasoning_time: float

# FileRef is a lightweight reference to a file with essential metadata.
# Used in chat inputs/context instead of full File objects.
class FileRef(TypedDict, total=False):
    id: str
    uri: str
    filename: str
    content_type: str
    size: int

# Tool represents a tool definition for LLM function calling
class Tool(TypedDict, total=False):
    type: ToolCallType
    function: ToolFunction

class ToolFunction(TypedDict, total=False):
    name: str
    description: str
    parameters: ToolParameters
    required: Optional[List[str]]

class ToolParameters(TypedDict, total=False):
    type: ToolParamType
    title: str
    properties: ToolParameterProperties
    required: Optional[List[str]]

ToolParameterProperties = Dict[str, "ToolParameterProperty"]

class ToolParameterProperty(TypedDict, total=False):
    type: ToolParamType
    title: str
    description: str
    properties: Optional[ToolParameterProperties]
    items: Optional[ToolParameterProperty]
    required: Optional[List[str]]

class ChatMessageRole(str, Enum):
    # LLM wire-protocol roles
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"
    # Internal bookkeeping roles — never sent to the LLM provider.
    # BuildContext converts these to system messages or skips them.
    INJECTION = "injection"
    COMPACTION = "compaction"

# Tool call types
class ToolCallType(str, Enum):
    TOOL_TYPE_FUNCTION = "function"

# Tool parameter types
class ToolParamType(str, Enum):
    OBJECT = "object"
    STRING = "string"
    INTEGER = "integer"
    NUMBER = "number"
    BOOLEAN = "boolean"
    ARRAY = "array"
    NULL = "null"

