# Code generated by gotypegen. DO NOT EDIT.

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Any, Dict, List, Optional, TypedDict, Union
from datetime import datetime


##########
# source: models.go

# InternalToolsConfig controls which built-in tools are enabled for an agent
class InternalToolsConfig(TypedDict, total=False):
    plan: Optional[bool]
    memory: Optional[bool]
    widget: Optional[bool]
    finish: Optional[bool]
    skills: Optional[bool]
    host_context: Optional[bool]

# AgentTool represents a unified tool that can be used by an agent
class AgentTool(TypedDict, total=False):
    name: str
    display_name: str
    description: str
    type: str
    require_approval: bool
    app: Optional[AppToolConfig]
    agent: Optional[AgentToolConfig]
    hook: Optional[HookToolConfig]
    http: Optional[HTTPToolConfig]
    call: Optional[HTTPToolConfig]
    mcp: Optional[MCPToolConfig]
    client: Optional[ClientToolConfig]
    internal: Optional[InternalToolConfig]

# InternalToolConfig contains configuration for internal/built-in tools
class InternalToolConfig(TypedDict, total=False):
    category: str
    operation: str

# SkillConfig defines a skill available to the agent.
class SkillConfig(TypedDict, total=False):
    name: str
    description: str
    skill_id: str
    version_id: str
    url: str
    content: str
    preload: bool

# ContextField declares a context parameter expected by the agent.
class ContextField(TypedDict, total=False):
    name: str
    description: str
    required: bool
    default: str

class AppToolConfig(TypedDict, total=False):
    ref: str
    id: str
    version_id: str
    function: str
    session_enabled: bool
    setup: Optional[Any]
    input: Optional[Any]

class AgentToolConfig(TypedDict, total=False):
    ref: str
    id: str
    version_id: str

class HookToolConfig(TypedDict, total=False):
    url: str
    secret: str
    input_schema: Optional[Any]
    output_schema: Optional[Any]

class ClientToolConfig(TypedDict, total=False):
    input_schema: Optional[Any]
    output_schema: Optional[Any]

# ToolAuthConfig declares how a tool authenticates.
class ToolAuthConfig(TypedDict, total=False):
    type: str
    provider: str
    integration_id: str
    secret: str
    header: str

class HTTPToolConfig(TypedDict, total=False):
    url: str
    method: str
    auth: Optional[ToolAuthConfig]
    headers: Dict[str, str]
    input_schema: Any
    output_schema: Any

class MCPToolConfig(TypedDict, total=False):
    integration_id: str
    tool_name: str

# AgentConfigInput is the API input shape for agent version config.
# Mirrors AgentConfig's JSON contract without gorm tags or runtime pointers.
class AgentConfigInput(TypedDict, total=False):
    name: str
    description: str
    system_prompt: str
    example_prompts: List[str]
    core_app: Optional[CoreAppConfigInput]
    tools: List[Optional[AgentTool]]
    skills: List[SkillConfig]
    context: List[ContextField]
    internal_tools: Optional[InternalToolsConfig]
    output_schema: Optional[Any]

# CoreAppConfigInput is the API input shape for core app configuration.
class CoreAppConfigInput(TypedDict, total=False):
    id: Optional[str]
    version_id: Optional[str]
    ref: Optional[str]
    setup: Optional[Any]
    input: Optional[Any]

class APIResponse(TypedDict, total=False):
    success: bool
    status: int
    data: Any
    error: Optional[APIError]

class APIError(TypedDict, total=False):
    code: str
    message: str
    suggestions: List[str]
    meta: Dict[str, Any]

# ApiAppRunRequest is the request body for /apps/run endpoint.
class ApiAppRunRequest(TypedDict, total=False):
    app: str
    app_id: str
    version_id: str
    infra: Optional[Infra]
    workers: Optional[List[str]]
    webhook: Optional[str]
    setup: Optional[Any]
    input: Any
    stream: bool
    wait: bool
    function: Optional[str]
    session: Optional[str]
    session_timeout: Optional[int]
    run_at: Optional[str]
    metadata: Optional[TaskMetadata]

# ApiAgentRunRequest is the request body for /agents/run endpoint.
class ApiAgentRunRequest(TypedDict, total=False):
    chat_id: Optional[str]
    agent: Optional[str]
    agent_config: Optional[AgentConfigInput]
    agent_name: Optional[str]
    input: ChatTaskInput
    context: Dict[str, str]
    stream: bool

class SkillPublishRequest(TypedDict, total=False):
    namespace: str
    name: str
    description: str
    category: str
    repo_url: str
    license: str
    allowed_tools: str
    compatibility: str
    instructions: str
    files: List[KnowledgeFile]
    metadata: Dict[str, str]
    parent_skill_id: str
    parent_version_id: str
    source_url: str
    version_notes: str
    disable_model_invocation: bool
    user_invocable: Optional[bool]
    context: str

# KnowledgeFile represents a file in a knowledge entry
class KnowledgeFile(TypedDict, total=False):
    path: str
    uri: str
    size: int
    hash: str
    content: str

# ChatTaskInput is the input envelope for a chat LLM task
class ChatTaskInput(TypedDict, total=False):
    model: Optional[str]
    context_size: int
    temperature: Optional[float]
    top_p: Optional[float]
    reasoning_effort: Optional[str]
    reasoning_max_tokens: Optional[int]
    system_prompt: str
    context: List[ChatTaskContextMessage]
    role: ChatMessageRole
    text: Optional[str]
    reasoning: Optional[str]
    # Attachments is the SDK input field with full file metadata
    attachments: Optional[List[FileRef]]
    # Images and Files are internal fields for task workers (filled from Attachments or context)
    images: Optional[List[str]]
    files: Optional[List[str]]
    tools: Optional[List[Tool]]
    tool_call_id: Optional[str]

# ChatTaskContextMessage represents a message in the chat context for LLM tasks
class ChatTaskContextMessage(TypedDict, total=False):
    role: ChatMessageRole
    text: Optional[str]
    reasoning: Optional[str]
    images: Optional[List[str]]
    files: Optional[List[str]]
    tools: Optional[List[Tool]]
    tool_calls: Optional[List[ToolCall]]
    tool_call_id: Optional[str]

StringEncodedMap = Dict[str, Any]

# TaskAction defines an action to execute when a task reaches a specific status.
class TaskAction(TypedDict, total=False):
    key: str
    on: str
    params: Any

# TaskMetadata holds optional metadata attached to a task.
class TaskMetadata(TypedDict, total=False):
    action: Optional[TaskAction]

# ToolCall represents a tool call from an LLM response (wire format)
# This is a transport object for parsing LLM responses, not a database model
class ToolCall(TypedDict, total=False):
    id: str
    type: str
    function: ToolCallFunction

# ToolCallFunction contains the function name and arguments from an LLM tool call
class ToolCallFunction(TypedDict, total=False):
    name: str
    arguments: StringEncodedMap

# FileRef is a lightweight reference to a file with essential metadata.
# Used in chat inputs/context instead of full File objects.
class FileRef(TypedDict, total=False):
    id: str
    uri: str
    filename: str
    content_type: str
    size: int

# Tool represents a tool definition for LLM function calling
class Tool(TypedDict, total=False):
    type: str
    function: ToolFunction

class ToolFunction(TypedDict, total=False):
    name: str
    description: str
    parameters: ToolParameters
    required: Optional[List[str]]

class ToolParameters(TypedDict, total=False):
    type: str
    title: str
    properties: ToolParameterProperties
    required: Optional[List[str]]

ToolParameterProperties = Dict[str, "ToolParameterProperty"]

class ToolParameterProperty(TypedDict, total=False):
    type: str
    title: str
    description: str
    properties: Optional[ToolParameterProperties]
    items: Optional[ToolParameterProperty]
    required: Optional[List[str]]

class ChatMessageRole(str, Enum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"

class Infra(str, Enum):
    PRIVATE = "private"
    CLOUD = "cloud"
    PRIVATE_FIRST = "private_first"

