# Code generated by gotypegen. DO NOT EDIT.

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Any, Dict, List, Optional, TypedDict, Union
from datetime import datetime


##########
# source: models.go

# InternalToolsConfig controls which built-in tools are enabled for an agent
class InternalToolsConfig(TypedDict, total=False):
    plan: Optional[bool]
    memory: Optional[bool]
    widget: Optional[bool]
    finish: Optional[bool]
    skills: Optional[bool]
    host_context: Optional[bool]
    meta: Optional[bool]

# AgentTool represents a unified tool that can be used by an agent
class AgentTool(TypedDict, total=False):
    name: str
    display_name: str
    description: str
    type: ToolType
    require_approval: bool
    app: Optional[AppToolConfig]
    agent: Optional[AgentToolConfig]
    hook: Optional[HookToolConfig]
    http: Optional[HTTPToolConfig]
    call: Optional[HTTPToolConfig]
    mcp: Optional[MCPToolConfig]
    client: Optional[ClientToolConfig]
    internal: Optional[InternalToolConfig]

# InternalToolConfig contains configuration for internal/built-in tools
class InternalToolConfig(TypedDict, total=False):
    category: str
    operation: str

# SkillConfig defines a skill available to the agent.
class SkillConfig(TypedDict, total=False):
    name: str
    description: str
    skill_id: str
    version_id: str
    url: str
    content: str
    preload: bool

# ContextField declares a context parameter expected by the agent.
class ContextField(TypedDict, total=False):
    name: str
    description: str
    required: bool
    default: str

# AgentToolDTO for API responses
class AgentToolDTO(TypedDict, total=False):
    name: str
    display_name: str
    description: str
    type: ToolType
    require_approval: bool
    app: Optional[AppToolConfigDTO]
    agent: Optional[AgentToolConfigDTO]
    hook: Optional[HookToolConfigDTO]
    http: Optional[HTTPToolConfigDTO]
    call: Optional[HTTPToolConfigDTO]
    mcp: Optional[MCPToolConfigDTO]
    client: Optional[ClientToolConfigDTO]

class AppToolConfig(TypedDict, total=False):
    ref: str
    id: str
    version_id: str
    function: str
    session_enabled: bool
    setup: Optional[Any]
    input: Optional[Any]

class AgentToolConfig(TypedDict, total=False):
    ref: str
    id: str
    version_id: str

class HookToolConfig(TypedDict, total=False):
    url: str
    secret: str
    input_schema: Optional[Any]
    output_schema: Optional[Any]

class ClientToolConfig(TypedDict, total=False):
    input_schema: Optional[Any]
    output_schema: Optional[Any]

# ToolAuthConfig declares how a tool authenticates.
class ToolAuthConfig(TypedDict, total=False):
    type: str
    provider: str
    integration_id: str
    secret: str
    header: str

class HTTPToolConfig(TypedDict, total=False):
    url: str
    method: str
    auth: Optional[ToolAuthConfig]
    headers: Dict[str, str]
    input_schema: Any
    output_schema: Any

class MCPToolConfig(TypedDict, total=False):
    integration_id: str
    tool_name: str

class AppToolConfigDTO(TypedDict, total=False):
    ref: str
    id: str
    version_id: str
    app: Optional[AppDTO]
    function: str
    session_enabled: bool
    setup: Optional[Any]
    input: Optional[Any]

class AgentToolConfigDTO(TypedDict, total=False):
    ref: str
    id: str
    version_id: str
    agent: Optional[AgentDTO]

class HookToolConfigDTO(TypedDict, total=False):
    url: str
    secret: str
    input_schema: Optional[Any]
    output_schema: Optional[Any]

class ClientToolConfigDTO(TypedDict, total=False):
    input_schema: Optional[Any]
    output_schema: Optional[Any]

class HTTPToolConfigDTO(TypedDict, total=False):
    url: str
    method: str
    auth: Optional[ToolAuthConfig]
    headers: Dict[str, str]
    input_schema: Any
    output_schema: Any

class MCPToolConfigDTO(TypedDict, total=False):
    integration_id: str
    tool_name: str

# AgentImages contains display images for an agent
class AgentImages(TypedDict, total=False):
    card: str
    thumbnail: str
    banner: str

# CoreAppConfigDTO references an app used as the agent's core
class CoreAppConfigDTO(TypedDict, total=False):
    id: Optional[str]
    version_id: Optional[str]
    ref: Optional[str]
    app: Optional[AppDTO]
    setup: Optional[Any]
    input: Optional[Any]

# CreateAgentRequest is the request body for POST /agents
# For new agents: omit ID, backend generates it
# For new version of existing agent: include ID
class CreateAgentRequest(TypedDict, total=False):
    id: str
    name: str
    namespace: str
    images: AgentImages
    # Version config (embedded - backend generates version ID, timestamps, etc)
    version: Optional[AgentConfigInput]

# AgentConfigInput is the API input shape for agent version config.
# Mirrors AgentConfig's JSON contract without gorm tags or runtime pointers.
class AgentConfigInput(TypedDict, total=False):
    name: str
    description: str
    system_prompt: str
    example_prompts: List[str]
    core_app: Optional[CoreAppConfigInput]
    tools: List[Optional[AgentTool]]
    skills: List[SkillConfig]
    context: List[ContextField]
    internal_tools: Optional[InternalToolsConfig]
    hooks: List[LifecycleHookConfig]
    output_schema: Optional[Any]

# CoreAppConfigInput is the API input shape for core app configuration.
class CoreAppConfigInput(TypedDict, total=False):
    id: Optional[str]
    version_id: Optional[str]
    ref: Optional[str]
    setup: Optional[Any]
    input: Optional[Any]

class APIResponse(TypedDict, total=False):
    success: bool
    status: int
    data: Any
    error: Optional[APIError]

class APIError(TypedDict, total=False):
    code: str
    message: str
    suggestions: List[str]
    meta: Dict[str, Any]

# ResponseMessage carries a non-error notice alongside a successful response.
# Inspired by GraphQL's coexisting data+errors pattern, but for actionable
# messages (warnings, info) rather than partial failures.
class ResponseMessage(TypedDict, total=False):
    level: str
    code: str
    message: str
    meta: Dict[str, Any]

# ApiAppRunRequest is the request body for /apps/run endpoint.
class ApiAppRunRequest(TypedDict, total=False):
    app: str
    app_id: str
    version_id: str
    infra: Optional[Infra]
    workers: Optional[List[str]]
    webhook: Optional[str]
    setup: Optional[Any]
    input: Any
    stream: bool
    wait: bool
    function: Optional[str]
    session: Optional[str]
    session_timeout: Optional[int]
    run_at: Optional[str]
    metadata: Optional[TaskMetadata]

# ApiAgentRunRequest is the request body for /agents/run endpoint.
class ApiAgentRunRequest(TypedDict, total=False):
    chat_id: Optional[str]
    agent: Optional[str]
    agent_config: Optional[AgentConfigInput]
    agent_name: Optional[str]
    input: LLMInput
    context: Dict[str, str]
    stream: bool

# CreateAgentMessageRequest is the request for creating agent messages.
class CreateAgentMessageRequest(TypedDict, total=False):
    chat_id: Optional[str]
    agent_id: Optional[str]
    agent_version_id: Optional[str]
    agent: Optional[str]
    tool_call_id: Optional[str]
    input: LLMInput
    integration_context: Optional[IntegrationContext]
    agent_config: Optional[AgentConfigInput]
    agent_name: Optional[str]
    context: Dict[str, str]

class CreateAgentMessageResponse(TypedDict, total=False):
    user_message: Optional[ChatMessageDTO]
    assistant_message: Optional[ChatMessageDTO]

# ToolResultRequest represents a tool result submission
class ToolResultRequest(TypedDict, total=False):
    result: str

# PartialFile is the clean DTO version (no gorm tags).
class PartialFile(TypedDict, total=False):
    uri: str
    path: Optional[str]
    content_type: Optional[str]
    size: Optional[int]
    filename: Optional[str]

class FileCreateRequest(TypedDict, total=False):
    category: str
    files: List[PartialFile]

# AppVersionInput is the API input shape for app version config (no gorm tags).
class AppVersionInput(TypedDict, total=False):
    metadata: Dict[str, Any]
    repository: str
    setup_schema: Any
    input_schema: Any
    output_schema: Any
    functions: Dict[str, AppFunction]
    default_function: str
    variants: Dict[str, AppVariant]
    env: Dict[str, str]
    kernel: str
    required_secrets: List[SecretRequirement]
    required_integrations: List[IntegrationRequirement]
    resources: AppResources

# CreateAppRequest is the request body for POST /apps
class CreateAppRequest(TypedDict, total=False):
    id: str
    namespace: str
    name: str
    description: str
    agent_description: str
    category: AppCategory
    images: AppImages
    version: Optional[AppVersionInput]
    preserve_current_version: bool

class SkillPublishRequest(TypedDict, total=False):
    namespace: str
    name: str
    description: str
    category: str
    repo_url: str
    license: str
    allowed_tools: str
    compatibility: str
    instructions: str
    files: List[KnowledgeFile]
    metadata: Dict[str, str]
    parent_skill_id: str
    parent_version_id: str
    source_url: str
    version_notes: str
    disable_model_invocation: bool
    user_invocable: Optional[bool]
    context: str

class CheckoutCreateRequest(TypedDict, total=False):
    amount: int
    success_url: str
    cancel_url: str

class AuthResponse(TypedDict, total=False):
    user: Optional[UserDTO]
    session_id: str
    is_new: bool
    otp_required: bool
    redirect_to: str
    provider: str

# DeviceAuthInitRequest is the optional body for initiating device auth.
# TokenKind selects the credential minted on approval; empty means
# DeviceTokenKindAPIKey (legacy CLIs send no body).
class DeviceAuthInitRequest(TypedDict, total=False):
    token_kind: DeviceTokenKind
    code_challenge: str
    code_challenge_method: str

class DeviceAuthResponse(TypedDict, total=False):
    user_code: str
    device_code: str
    poll_url: str
    approve_url: str
    expires_in: int
    interval: int

class DeviceAuthPollResponse(TypedDict, total=False):
    status: DeviceAuthStatus
    # ApiKey is set for legacy device-auth API key logins.
    # TODO: remove once CLIs older than the session-token release are retired.
    api_key: str
    # SessionToken is set when the flow was initiated with token_kind=session.
    session_token: str
    team_id: str

class TeamCreateRequest(TypedDict, total=False):
    name: str
    username: str
    email: str

class TeamSetupRequest(TypedDict, total=False):
    username: str

class TeamMemberAddRequest(TypedDict, total=False):
    email: str
    role: TeamRole

class TeamMemberUpdateRoleRequest(TypedDict, total=False):
    role: TeamRole

class SecretCreateRequest(TypedDict, total=False):
    key: str
    value: str
    description: str

class SecretUpdateRequest(TypedDict, total=False):
    value: str
    description: Optional[str]

class IntegrationConnectRequest(TypedDict, total=False):
    provider: str
    type: str
    scopes: List[str]
    api_key: str
    metadata: Dict[str, Any]

class IntegrationCompleteOAuthRequest(TypedDict, total=False):
    provider: str
    type: str
    code: str
    state: str
    code_verifier: str

class IntegrationConnectResponse(TypedDict, total=False):
    integration: Optional[IntegrationDTO]
    auth_url: str
    state: str
    code_verifier: str
    instructions: str
    requires_confirmation: bool
    confirmation_type: str
    message: str

class ProjectCreateRequest(TypedDict, total=False):
    name: str
    type: ProjectType

class ProjectUpdateRequest(TypedDict, total=False):
    name: str

class MoveAgentToProjectRequest(TypedDict, total=False):
    agent_id: str
    project_id: str

# CancelTaskRequest is the optional request body for task cancellation.
class CancelTaskRequest(TypedDict, total=False):
    force: bool
    timeout: int

class CreateApiKeyRequest(TypedDict, total=False):
    name: str
    expires_at: Optional[str]
    scopes: List[str]

# EstimateCostRequest is the request for POST /store/apps/{appId}/estimate.
class EstimateCostRequest(TypedDict, total=False):
    input: Any
    function: str

# EstimateCostResponse is the response from the cost estimation endpoint.
class EstimateCostResponse(TypedDict, total=False):
    # Confidence: "exact" (all fees input-based), "range" (estimate expression),
    # or "unknown" (output-dependent, no estimate expression).
    confidence: str
    # Microcents is set when confidence is "exact".
    microcents: Optional[int]
    # Min/Max are set when confidence is "range".
    min: Optional[int]
    max: Optional[int]
    # DependsOn lists post-execution variables the pricing needs (when not exact).
    depends_on: List[str]
    # EstimateError is set when an estimate expression exists but failed to evaluate.
    estimate_error: str
    # PricingDescription is the rendered human-readable pricing string.
    pricing_description: str

# ScopeDefinition describes a single scope for UI rendering
class ScopeDefinition(TypedDict, total=False):
    value: Scope
    label: str
    description: str
    group: ScopeGroup

# ScopeGroupDefinition describes a group of scopes for UI rendering
class ScopeGroupDefinition(TypedDict, total=False):
    id: ScopeGroup
    label: str
    description: str

# ScopesResponse is the API response for GET /scopes
class ScopesResponse(TypedDict, total=False):
    scopes: List[ScopeDefinition]
    groups: List[ScopeGroupDefinition]
    presets: List[ScopePreset]

# ScopePreset represents a predefined bundle of scopes for common use cases
class ScopePreset(TypedDict, total=False):
    id: str
    label: str
    description: str
    scopes: List[Scope]
    summary: List[str]
    hidden: bool

# AppPricing configures all pricing using CEL expressions.
# Empty expressions use defaults. All values in microcents.
class AppPricing(TypedDict, total=False):
    prices: Dict[str, int]
    upstream_pricing: str
    resource_expression: str
    inference_expression: str
    royalty_expression: str
    partner_expression: str
    total_expression: str
    # Estimate is a single CEL expression for pre-execution cost estimation.
    # Returns either an int (exact total in microcents) or a {"min": int, "max": int} map.
    # Only has access to pre-execution variables: task_inputs, prices, fees, task_function.
    # Used by the /estimate endpoint when the real expressions depend on post-execution data.
    # Not needed when all fee expressions are already input-based (the system evaluates those directly).
    estimate: str
    # Estimable is computed at save time. True when all fee expressions can be
    # evaluated from pre-execution data alone (task_inputs, prices, fees, task_function).
    estimable: Optional[bool]
    description: str
    description_rendered: str

# AppFunction represents a callable entry point within an app version.
class AppFunction(TypedDict, total=False):
    name: str
    description: str
    input_schema: Any
    output_schema: Any

# AppImages holds developer-provided images for the app.
class AppImages(TypedDict, total=False):
    card: str
    thumbnail: str
    banner: str

# AppGPUResource describes GPU requirements.
class AppGPUResource(TypedDict, total=False):
    count: int
    vram: int
    type: GPUType

# AppResources describes resource requirements.
class AppResources(TypedDict, total=False):
    gpu: AppGPUResource
    ram: int

# AppVariant is a named resource/env configuration variant.
class AppVariant(TypedDict, total=False):
    name: str
    order: int
    resources: AppResources
    env: Dict[str, str]
    python: str

# SecretRequirement defines a secret that an app requires to run.
class SecretRequirement(TypedDict, total=False):
    key: str
    description: str
    optional: bool

# IntegrationRequirement defines an integration that an app requires.
# Key is the provider slug (e.g. "bytedance", "google").
# Secrets lists the specific env var names to inject from this integration.
# Scopes lists OAuth scopes needed (for OAuth integrations).
class IntegrationRequirement(TypedDict, total=False):
    key: str
    description: str
    optional: bool
    secrets: List[str]
    scopes: List[str]

# AppStoreListingDTO for API responses
class AppStoreListingDTO(TypedDict, total=False):
    id: str
    created_at: str
    updated_at: str
    deleted_at: Optional[str]
    category: str
    subcategory: str
    page_id: Optional[str]
    is_featured: bool
    rank: int
    allows_private_workers: bool
    allows_cloud_workers: bool
    max_concurrency: int
    max_concurrency_per_team: int
    min_concurrency: int
    required_feature: str
    tags: List[str]

# PublicAppStoreDTO is a lean DTO for public app store display.
class PublicAppStoreDTO(TypedDict, total=False):
    id: str
    category: str
    subcategory: str
    tags: List[str]
    namespace: str
    name: str
    description: str
    images: AppImages
    is_featured: bool
    rank: int
    has_approved_version: bool
    page_id: Optional[str]
    pricing_description: str

# AuthSessionDTO is a safe representation of AuthSession for API responses.
class AuthSessionDTO(TypedDict, total=False):
    id: str
    created_at: str
    expires_at: str
    ip: str
    city: str
    country: str
    country_code: str
    region: str
    os: str
    browser: str
    browser_version: str
    auth_method: str
    scopes: List[Scope]
    current: bool

# BaseModelDTO is the contract-layer base embed — same fields, no gorm tags.
# All DTOs should embed this instead of BaseModel.
class BaseModelDTO(TypedDict, total=False):
    id: str
    short_id: str
    created_at: str
    updated_at: str
    deleted_at: Optional[str]

# PermissionModelDTO is the contract-layer permission embed.
class PermissionModelDTO(TypedDict, total=False):
    user_id: str
    user: Optional[UserRelationDTO]
    team_id: str
    team: Optional[TeamRelationDTO]
    visibility: Visibility

# ResourceStatusDTO is a lightweight status-only response for polling transports.
class ResourceStatusDTO(TypedDict, total=False):
    id: str
    status: Any
    updated_at: str

# AvailabilityResponse answers "can I use this name?" — for page slugs, team
# usernames and voucher codes alike.
# 
# The three checks had three different shapes, and one of them was an untyped
# map[string]bool that generated no client type at all, so each caller invented
# its own handling. Reason exists because "not available" was previously
# indistinguishable from "reserved": every client that wanted to say why had to
# mirror the server's reserved-name list to guess, and those mirrors went stale.
class AvailabilityResponse(TypedDict, total=False):
    # Value is the normalized form of what was checked — the server may slugify
    # or lowercase the input, and the client should show what it actually took.
    value: str
    available: bool
    # Reason is set only when Available is false: "taken" or "reserved".
    reason: str

# SubmitBountyRequest is used to claim a bounty reward.
class SubmitBountyRequest(TypedDict, total=False):
    bounty_id: str
    proof_id: str
    agent: str
    source: str

# SubmitBountyResponse is returned when claiming a bounty.
class SubmitBountyResponse(TypedDict, total=False):
    submission: BountySubmissionDTO
    granted_amount: int

# SearchRequest represents a search request.
# Each model declares its own SearchFields() on the repository.
class SearchRequest(TypedDict, total=False):
    term: str
    exact: bool

# Filter represents a single filter condition
class Filter(TypedDict, total=False):
    field: str
    operator: FilterOperator
    value: Any

# SortOrder represents sorting configuration
class SortOrder(TypedDict, total=False):
    field: str
    dir: str

# CursorListRequest represents a cursor-based list request with all options
class CursorListRequest(TypedDict, total=False):
    cursor: str
    page: Optional[int]
    limit: int
    direction: str
    search: Optional[SearchRequest]
    filters: List[Filter]
    preloads: List[str]
    sort: List[SortOrder]
    fields: List[str]
    permissions: List[str]
    include_others: bool

# CursorListResponse represents a cursor-based paginated response
class CursorListResponse(TypedDict, total=False):
    items: List[Any]
    next_cursor: str
    prev_cursor: str
    has_next: bool
    has_previous: bool
    items_per_page: int
    total_items: int

# CountResponse is the response for count endpoints.
class CountResponse(TypedDict, total=False):
    count: int

# EngineConfig holds engine configuration (no gorm tags).
class EngineConfig(TypedDict, total=False):
    id: str
    name: str
    api_url: str
    engine_port: str
    workers: WorkerConfig
    api_key: str
    container_mode: bool
    network_name: str
    cache_path: str
    gpus: List[str]
    callback_base_port: int
    engine_internal_api_url: str

# WorkerGPUConfig defines GPU allocation for a worker.
class WorkerGPUConfig(TypedDict, total=False):
    gpus: List[Any]

# WorkerCPUConfig defines CPU allocation for a worker.
class WorkerCPUConfig(TypedDict, total=False):
    count: int

# WorkerConfig defines how workers are allocated on an engine.
class WorkerConfig(TypedDict, total=False):
    gpu: List[WorkerGPUConfig]
    cpu: WorkerCPUConfig

# WorkerSummary is a lightweight worker response.
class WorkerSummary(TypedDict, total=False):
    id: str
    user_id: str
    index: int
    status: WorkerStatus
    engine_id: str
    engine_name: str
    task_id: Optional[str]
    app_id: str
    app_version_id: str
    active_session_id: Optional[str]
    gpus: List[WorkerGPU]
    cpus: List[WorkerCPU]
    rams: List[WorkerRAM]

# WorkerGPU describes a GPU attached to a worker (contract-only, no gorm).
class WorkerGPU(TypedDict, total=False):
    id: str
    worker_id: str
    gpu_id: str
    type: GPUType
    name: str
    vram: int

# WorkerCPU describes a CPU attached to a worker (contract-only, no gorm).
class WorkerCPU(TypedDict, total=False):
    id: str
    worker_id: str
    name: str
    vendor_id: str
    family: str
    model: str
    cores: int
    frequency: str

# WorkerRAM describes RAM attached to a worker (contract-only, no gorm).
class WorkerRAM(TypedDict, total=False):
    id: str
    worker_id: str
    total: int

# EntitlementErrorMeta is the structured metadata returned in entitlement error responses.
class EntitlementErrorMeta(TypedDict, total=False):
    resource: EntitlementResource
    resource_label: str
    limit: Optional[int]
    current: Optional[int]
    upgrade_available: bool
    addon_plan_id: str
    addon_plan_name: str
    addon_plan_price: Optional[int]

# FileMetadata holds probed media metadata cached on File records.
class FileMetadata(TypedDict, total=False):
    type: str
    width: int
    height: int
    duration: float
    fps: float
    sample_rate: int
    channels: int
    codec: str

# FlowNodeData describes a node's data within a flow
class FlowNodeData(TypedDict, total=False):
    app: Optional[AppDTO]
    app_id: str
    app_version_id: str
    function: str
    infra: Infra
    workers: List[str]
    setup: Optional[Any]
    additional: Optional[Any]
    task: Optional[TaskDTO]
    task_id: Optional[str]

# FlowNodeDataMap maps node IDs to their data
FlowNodeDataMap = Dict[str, "FlowNodeData"]

# NodeTaskDTO represents a node task reference
class NodeTaskDTO(TypedDict, total=False):
    task_id: str
    task: Optional[TaskDTO]

# FlowAction represents a single graph mutation.
class FlowAction(TypedDict, total=False):
    type: FlowActionType
    payload: Any

# FlowActionsRequest is the request body for POST /flows/{id}/actions.
class FlowActionsRequest(TypedDict, total=False):
    actions: List[FlowAction]

# FlowActionsResponse is the response from the actions endpoint.
class FlowActionsResponse(TypedDict, total=False):
    version: int
    actions: List[FlowAction]
    errors: List[FlowActionError]

# FlowActionError is an error returned from an action.
class FlowActionError(TypedDict, total=False):
    type: str
    message: str

class AddNodePayload(TypedDict, total=False):
    id: str
    type: str
    position: FlowNodePosition
    data: FlowNodeData

class RemoveNodePayload(TypedDict, total=False):
    id: str

class MoveNodePayload(TypedDict, total=False):
    id: str
    position: FlowNodePosition

class MoveNodesPayload(TypedDict, total=False):
    positions: Dict[str, FlowNodePosition]

class DuplicateNodePayload(TypedDict, total=False):
    source_id: str
    new_id: str
    offset: FlowNodePosition

class RenameNodePayload(TypedDict, total=False):
    old_id: str
    new_id: str

class SetNodeAppPayload(TypedDict, total=False):
    node_id: str
    app_id: str
    app_version_id: str
    function: str

class UpdateNodeDataPayload(TypedDict, total=False):
    node_id: str
    patch: Dict[str, Any]

class SetInputPayload(TypedDict, total=False):
    node_id: str
    input_key: str
    input: FlowRunInput

class ClearInputPayload(TypedDict, total=False):
    node_id: str
    input_key: str

class AddEdgePayload(TypedDict, total=False):
    id: str
    source: str
    target: str
    source_handle: Optional[str]
    target_handle: Optional[str]

class RemoveEdgePayload(TypedDict, total=False):
    id: str

class SetSchemaPayload(TypedDict, total=False):
    schema: Any

class SetOutputMappingPayload(TypedDict, total=False):
    field: str
    mapping: OutputFieldMapping

class RemoveOutputMappingPayload(TypedDict, total=False):
    field: str

class RenameOutputFieldPayload(TypedDict, total=False):
    old_field: str
    new_field: str

# ChatTraceDTO is the trace response for chat observability
class ChatTraceDTO(TypedDict, total=False):
    graph_id: str
    nodes: List[Optional[GraphNodeDTO]]
    edges: List[Optional[GraphEdgeDTO]]
    total_steps: int
    completed_steps: int
    running_steps: int
    failed_steps: int

class InstanceTypeConfiguration(TypedDict, total=False):
    gpu_type: str
    gpu_manufacturer: str
    interconnect: str
    memory_in_gb: int
    num_gpus: int
    nvlink: bool
    os_options: List[str]
    storage_in_gb: int
    vcpus: int
    vram_per_gpu_in_gb: int

class InstanceTypeAvailability(TypedDict, total=False):
    available: bool
    region: str

class InstanceTypeBootTime(TypedDict, total=False):
    average_seconds: int
    updated_at: str
    sample_size: int

# IntegrationConfigDTO is the API response for integration configuration
class IntegrationConfigDTO(TypedDict, total=False):
    slug: str
    provider: str
    type: str
    auth: str
    name: str
    short_name: str
    description: str
    icon_url: str
    how_it_works: List[str]
    docs_url: str
    secret_fields: List[SecretFieldConfig]
    allows_byok: bool
    available: bool
    has_managed: bool
    grant: IntegrationGrant
    integration: Optional[IntegrationDTO]

# SecretFieldConfig defines a secret field for the UI
class SecretFieldConfig(TypedDict, total=False):
    key: str
    label: str
    placeholder: str
    sensitive: bool
    optional: bool

# KnowledgeFile represents a file in a knowledge entry
class KnowledgeFile(TypedDict, total=False):
    path: str
    uri: str
    size: int
    hash: str
    content: str

# ResourceRef is a compact reference to any resource (knowledge, app, agent).
class ResourceRef(TypedDict, total=False):
    id: str
    namespace: str
    name: str
    type: ResourceType
    resource_kind: str
    description: str

# ReferencesResponse is returned by the references endpoint.
class ReferencesResponse(TypedDict, total=False):
    resource: ResourceRef
    references: List[ResourceRef]
    referenced_by: List[ResourceRef]

# SkillLineageResponse is returned by the lineage endpoint.
class SkillLineageResponse(TypedDict, total=False):
    skill: SkillLineageSkillRef
    parents: List[SkillLineageSkillRef]
    siblings: List[SkillLineageSkillRef]
    forks: List[SkillLineageSkillRef]
    duplicates: List[SkillLineageSkillRef]
    fork_depth: int

# SkillLineageSkillRef is a compact skill reference for lineage responses.
class SkillLineageSkillRef(TypedDict, total=False):
    id: str
    namespace: str
    name: str
    version_count: int
    parent_version_id: str
    versions_since_fork: int

# PublicSkillStoreDTO for public skill store display
class PublicSkillStoreDTO(TypedDict, total=False):
    id: str
    category: str
    tags: List[str]
    namespace: str
    name: str
    description: str
    is_featured: bool
    rank: int
    has_approved_version: bool

# SkillStoreListingDTO for API responses
class SkillStoreListingDTO(TypedDict, total=False):
    id: str
    created_at: str
    updated_at: str
    deleted_at: Optional[str]
    category: str
    is_featured: bool
    rank: int
    installs: int
    uses: int
    tags: List[str]

# LifecycleHookConfig registers a handler for an agent lifecycle event.
# Stored on AgentVersion alongside Tools and Skills.
class LifecycleHookConfig(TypedDict, total=False):
    event: HookEvent
    type: HookHandlerType
    handler: str
    async_: bool
    timeout: int
    # Gate-specific fields (type: "gate")
    default_resolution: InterruptResolution

# LifecycleHookPayload is sent to hook handlers on lifecycle events.
class LifecycleHookPayload(TypedDict, total=False):
    event: HookEvent
    timestamp: str
    agent_id: str
    chat_id: str
    run_id: str
    turn_count: int
    data: Any

# LifecycleHookResponse is returned by hook handlers.
# All fields are optional — an empty 200 response is equivalent to {decision: "allow"}.
class LifecycleHookResponse(TypedDict, total=False):
    inject: Optional[ContextInjection]
    decision: HookDecision
    reason: str
    override: Any
    system: str

# ContextInjection adds ephemeral content to the agent's context window.
# Injections are stored as ChatMessages and filtered at context-build time.
class ContextInjection(TypedDict, total=False):
    content: str
    role: str
    ttl_turns: int
    dedup_key: str

# ToolCallEventData is the typed payload for agent.tool_call events.
class ToolCallEventData(TypedDict, total=False):
    tool: str
    arguments: Dict[str, Any]

# ToolResultEventData is the typed payload for agent.tool_result events.
class ToolResultEventData(TypedDict, total=False):
    tool: str
    status: str
    result: str

# ErrorEventData is the typed payload for agent.error events.
class ErrorEventData(TypedDict, total=False):
    error: str

# ElicitationCapability advertises which elicitation modes the client handles.
# An empty struct is equivalent to form-only for backward compatibility.
class ElicitationCapability(TypedDict, total=False):
    form: Optional[Dict[str, Any]]
    url: Optional[Dict[str, Any]]

# ClientCapabilities advertises what a client can do.
class ClientCapabilities(TypedDict, total=False):
    elicitation: Optional[ElicitationCapability]

# InputRequest is a single server-to-client request inside an InputRequiredResult.
class InputRequest(TypedDict, total=False):
    method: str
    params: Any

# ElicitResult is the client's response to an elicitation/create request.
class ElicitResult(TypedDict, total=False):
    action: ElicitAction
    content: Dict[str, Any]

# ServerInfo represents information about the server
class ServerInfo(TypedDict, total=False):
    name: str
    title: str
    version: str

# ResultMeta is the _meta object attached to results. Servers SHOULD identify
# themselves in every result from 2026-07-28 onward (SEP-2575).
# 
# The struct tag is the single definition of the key — Go tags cannot reference
# a constant, so there is deliberately no MetaServerInfo const to drift from it.
ResultMeta = TypedDict('ResultMeta', {
    'io.modelcontextprotocol/serverInfo': 'Optional[ServerInfo]',
    # TTLMs and CacheScope are read-only legacy fields: servers older than
    # 2026-07-28 nested the caching signals here instead of on the result. They
    # live on this type rather than a separate one so a single decode of the
    # _meta object yields both them and serverInfo.
    'ttlMs': 'Optional[int]',
    'cacheScope': 'CacheScope',
}, total=False)

# ResourceContent represents resource content
class ResourceContent(TypedDict, total=False):
    uri: str
    name: str
    title: str
    mimeType: str
    text: str
    blob: str

# ToolCallRequest represents a request to call a tool.
# 
# InputResponses and RequestState are present on MRTR retries: the client is
# echoing back responses to the server's InputRequiredResult.
class ToolCallRequest(TypedDict, total=False):
    name: str
    arguments: Dict[str, Any]
    inputResponses: Dict[str, Any]
    requestState: str

# ToolCallResponse represents a response from a tool call.
# 
# ResultType is read as well as written: an inbound response carrying
# ResultTypeInputRequired is a Multi Round-Trip Request asking for more input,
# not tool output, and callers must not treat it as a result. Servers older than
# 2026-07-28 omit the field, which clients MUST read as "complete".
class ToolCallResponse(TypedDict, total=False):
    resultType: ResultType
    content: List[ToolContent]
    structuredContent: Any
    isError: bool
    _meta: Optional[ResultMeta]
    # MRTR fields — present when ResultType == ResultTypeInputRequired.
    inputRequests: Dict[str, InputRequest]
    requestState: str

# ToolContent represents content in a tool response
class ToolContent(TypedDict, total=False):
    type: ToolContentType
    text: str
    data: str
    mimeType: str
    resource: Optional[ResourceContent]

# StringSlice is a custom type for storing string slices
StringSlice = List[str]

# MCPServerDTO is the API response shape for the resource.
class MCPServerDTO(TypedDict, total=False):
    id: str
    slug: str
    name: str
    description: str
    icon_url: str
    server_url: str
    auth_type: MCPServerAuthType
    oauth_client_id: str
    default_scopes: StringSlice
    documentation_url: str

# UpdateNotificationPreferencesRequest is the request to update preferences
class UpdateNotificationPreferencesRequest(TypedDict, total=False):
    email_enabled: Optional[bool]
    sms_enabled: Optional[bool]
    push_enabled: Optional[bool]
    slack_enabled: Optional[bool]
    billing_notifications: Optional[bool]
    task_notifications: Optional[bool]
    system_notifications: Optional[bool]
    marketing_emails: Optional[bool]
    quiet_hours_enabled: Optional[bool]
    quiet_hours_start: Optional[str]
    quiet_hours_end: Optional[str]
    timezone: Optional[str]

# PageMetadata holds metadata for a page
class PageMetadata(TypedDict, total=False):
    title: str
    description: str
    image: str
    tags: List[str]
    order: int
    type: str
    icon: str
    hide_from_nav: bool
    action_url: str
    action_label: str
    display_mode: str
    # PublishAt is when a scheduled page goes live. Only meaningful while the
    # page's status is PageStatusScheduled.
    publish_at: Optional[str]

# MenuItem represents an item in a menu (can be nested)
class MenuItem(TypedDict, total=False):
    id: str
    label: str
    slug: str
    page_id: str
    url: str
    icon: str
    order: int
    is_group: bool
    expanded: bool
    children: List[MenuItem]

# PlanLimit defines a single resource limit or feature gate within a plan.
class PlanLimit(TypedDict, total=False):
    type: EntitlementType
    label: str
    unit: str
    enabled: bool
    unlimited: bool
    limit: int
    enforcement: EnforcementMode

# PlanLimits maps entitlement resources to their limits
PlanLimits = Dict["EntitlementResource", "PlanLimit"]

# ProjectModelDTO provides optional project association for DTOs
class ProjectModelDTO(TypedDict, total=False):
    project_id: Optional[str]
    project: Optional[ProjectDTO]

# KnowledgeCreateRequest is the request body for POST /knowledge.
class KnowledgeCreateRequest(TypedDict, total=False):
    name: str
    description: str
    repo_url: str
    type: KnowledgeType
    lifecycle: KnowledgeLifecycle
    # Version content (inline — creates first version)
    version: Optional[KnowledgeVersionInput]

# KnowledgeVersionInput is the input shape for creating/updating a knowledge version.
class KnowledgeVersionInput(TypedDict, total=False):
    description: str
    content: Optional[KnowledgeFile]
    files: List[KnowledgeFile]
    tags: List[str]
    scope: List[str]
    metadata: Dict[str, str]
    source_url: str
    mutation_type: str
    version_notes: str

# KnowledgeUpdateRequest is the request body for PUT /knowledge/{id}.
class KnowledgeUpdateRequest(TypedDict, total=False):
    description: str
    version: Optional[KnowledgeVersionInput]

# CreateSubscriptionRequest is the request body for POST /subscriptions.
class CreateSubscriptionRequest(TypedDict, total=False):
    plan_id: str
    interval: str
    success_url: str
    cancel_url: str

# ChangePlanRequest is the request body for POST /subscriptions/change.
class ChangePlanRequest(TypedDict, total=False):
    plan_id: str

# CancelSubscriptionRequest is the request body for POST /subscriptions/cancel.
class CancelSubscriptionRequest(TypedDict, total=False):
    at_period_end: Optional[bool]

# OAuthAuthorizeInfoResponse is returned by GET /oauth/authorize/info.
class OAuthAuthorizeInfoResponse(TypedDict, total=False):
    client_name: str
    client_type: str
    origin: str
    verified: bool
    scopes: List[Scope]
    redirect_host: str

# OAuthApproveRequest is the request body for POST /oauth/authorize/approve.
class OAuthApproveRequest(TypedDict, total=False):
    client_id: str
    redirect_uri: str
    code_challenge: str
    state: str
    scope: str

# OAuthRedirectResponse wraps a redirect URI.
class OAuthRedirectResponse(TypedDict, total=False):
    redirect_uri: str

# OAuthConnectedApp represents an authorized OAuth client.
class OAuthConnectedApp(TypedDict, total=False):
    client_id: str
    client_name: str
    client_type: str
    origin: str
    verified: bool
    scopes: str
    authorized_at: str

# SetVisibilityRequest is used by admin endpoints to set visibility.
class SetVisibilityRequest(TypedDict, total=False):
    visibility: str

# ChargeAmountRequest is the request for charging a saved payment method.
class ChargeAmountRequest(TypedDict, total=False):
    amount: int

# CompletePaymentRequest finishes a checkout or payment session.
class CompletePaymentRequest(TypedDict, total=False):
    session_id: str
    payment_id: str

# UpdateIntegrationScopesRequest updates integration scopes.
class UpdateIntegrationScopesRequest(TypedDict, total=False):
    scopes: List[str]

# SuggestRequest is the input for the suggest endpoint.
class SuggestRequest(TypedDict, total=False):
    query: str
    context: str
    limit: int
    category: str
    agent: bool
    scope: List[str]

# SuggestResponse is the output of the suggest endpoint.
class SuggestResponse(TypedDict, total=False):
    query: str
    results: List[SuggestResult]

# SuggestResult is a single result item from the suggest endpoint.
class SuggestResult(TypedDict, total=False):
    type: str
    tag: str
    name: str
    description: str
    command: str
    score: float

# RequirementError represents a single missing requirement with actionable info
class RequirementError(TypedDict, total=False):
    type: RequirementType
    key: str
    message: str
    action: Optional[SetupAction]

# SetupAction provides actionable info for resolving a missing requirement
class SetupAction(TypedDict, total=False):
    type: SetupActionType
    provider: str
    provider_name: str
    scopes: List[str]
    scope_descriptions: Dict[str, str]

# CheckRequirementsRequest is the request body for checking requirements
class CheckRequirementsRequest(TypedDict, total=False):
    secrets: List[SecretRequirement]
    integrations: List[IntegrationRequirement]

# CheckRequirementsResponse is the API response for checking requirements
class CheckRequirementsResponse(TypedDict, total=False):
    satisfied: bool
    errors: List[RequirementError]

class ShareRequest(TypedDict, total=False):
    user_id: str
    permission: Permission

# SDKTypes is a phantom type for gotypegen dependency tracing.
# Types listed here (and their transitive dependencies) are included
# in the generated SDK output (TypeScript, Python, Go).
# 
# To expose a type to SDK consumers: reference it in this struct.
class SDKTypes(TypedDict, total=False):
    pass

# Hardware/System related types
class SystemInfo(TypedDict, total=False):
    hostname: str
    engine_version: str
    ipv4: str
    ipv6: str
    mac_address: str
    os: str
    docker: Docker
    wsl2: WSL2
    cpus: List[CPU]
    ram: RAM
    volumes: List[Volume]
    hf_cache: HFCacheInfo
    gpus: List[GPU]

class Docker(TypedDict, total=False):
    binary_path: str
    installed: bool
    socket_path: str
    socket_available: bool
    running: bool
    version: str

class WSL2(TypedDict, total=False):
    installed: bool
    enabled: bool
    version: str

class CPU(TypedDict, total=False):
    name: str
    vendor_id: str
    family: str
    model: str
    cores: int
    frequency: str
    usage: float
    normalized_usage: float

class Volume(TypedDict, total=False):
    name: str
    size: int
    used: int
    free: int
    usage: float

class RAM(TypedDict, total=False):
    total: int
    available: int
    used: int
    free: int
    usage: float
    total_physical: int
    total_usable: int
    bootloader_usage: int
    swap_total: int
    swap_used: int
    swap_free: int
    swap_usage: float

class GPU(TypedDict, total=False):
    id: str
    name: str
    index: int
    cuda_version: str
    driver_version: str
    memory_used: int
    memory_total: int
    temperature: int

# CachedRevisionInfo represents information about a cached revision
class CachedRevisionInfo(TypedDict, total=False):
    commit_hash: str
    snapshot_path: str
    last_modified: str
    size_on_disk: int
    size_on_disk_str: str
    nb_files: int
    refs: List[str]

# CachedRepoInfo represents information about a cached repository
class CachedRepoInfo(TypedDict, total=False):
    repo_id: str
    repo_type: str
    repo_path: str
    last_accessed: str
    last_modified: str
    size_on_disk: int
    size_on_disk_str: str
    nb_files: int
    refs: List[str]
    revisions: List[CachedRevisionInfo]

# HFCacheInfo represents information about the Huggingface cache
class HFCacheInfo(TypedDict, total=False):
    cache_dir: str
    repos: List[CachedRepoInfo]
    size_on_disk: int
    warnings: List[str]

# TaskEvent represents a single status transition event.
# Duplicated here (no gorm tags) so DTOs can reference it without importing models.
class TaskEvent(TypedDict, total=False):
    id: str
    created_at: str
    event_time: str
    task_id: str
    status: TaskStatus

# TaskLog represents a single log entry for a task.
class TaskLog(TypedDict, total=False):
    id: str
    created_at: str
    updated_at: str
    task_id: str
    log_type: TaskLogType
    content: bytes

# TaskResultDTO is a slim response for task run/result endpoints.
class TaskResultDTO(TypedDict, total=False):
    id: str
    short_id: str
    status: TaskStatus
    status_text: str
    output: Any
    error: Optional[str]
    session_id: Optional[str]
    created_at: str
    updated_at: str
    run_at: Optional[str]

# TaskLogsDTO is a lightweight response for task logs endpoint.
class TaskLogsDTO(TypedDict, total=False):
    task_id: str
    status: TaskStatus
    events: List[TaskEvent]
    logs: List[TaskLog]

# TaskTimingGroup represents a high-level phase of task execution with its duration.
class TaskTimingGroup(TypedDict, total=False):
    label: str
    start_at: str
    end_at: str
    duration: str
    duration_ms: int

# TaskTimingEvent represents a single status transition with the time spent before the next transition.
class TaskTimingEvent(TypedDict, total=False):
    status: str
    timestamp: str
    duration: str
    duration_ms: int
    next_status: str

# TaskTimingsDTO is the response for the task timings endpoint.
class TaskTimingsDTO(TypedDict, total=False):
    task_id: str
    status: TaskStatus
    total_duration: str
    total_duration_ms: int
    groups: List[TaskTimingGroup]
    events: List[TaskTimingEvent]

# TeamMemberDTO is the API response for a team member.
class TeamMemberDTO(TypedDict, total=False):
    id: str
    user_id: str
    team_id: str
    role: TeamRole
    user: Optional[TeamMemberUserDTO]

# TeamMemberUserDTO is a lightweight user view within team membership.
class TeamMemberUserDTO(TypedDict, total=False):
    id: str
    email: str
    name: str
    full_name: str
    avatar_url: str

# TeamRelationDTO is a lightweight team reference embedded in other DTOs.
class TeamRelationDTO(TypedDict, total=False):
    id: str
    created_at: str
    updated_at: str
    type: TeamType
    username: str
    avatar_url: str
    setup_completed: bool

# TeamInviteDTO is the public representation of an invite
class TeamInviteDTO(TypedDict, total=False):
    id: str
    team_id: str
    email: str
    role: TeamRole
    status: TeamInviteStatus
    expires_at: str
    created_at: str
    invited_by: Optional[TeamMemberUserDTO]
    team: Optional[TeamRelationDTO]

# TeamInviteCreateRequest is used when creating a team invite
class TeamInviteCreateRequest(TypedDict, total=False):
    email: str
    role: TeamRole

# ToolInvocationFunction contains the function details for a tool invocation
class ToolInvocationFunction(TypedDict, total=False):
    name: str
    arguments: StringEncodedMap

# MetaItem represents metadata about an input or output item
class MetaItem(TypedDict, total=False):
    type: MetaItemType
    tokens: int
    width: int
    height: int
    resolution_mp: float
    steps: int
    count: int
    resolution: VideoResolution
    seconds: float
    fps: int
    sample_rate: int
    cost: float
    extra: Dict[str, Any]

# OutputMeta contains structured metadata about task inputs and outputs for pricing calculation
class OutputMeta(TypedDict, total=False):
    inputs: List[MetaItem]
    outputs: List[MetaItem]

# UserRelationDTO is a lightweight user reference embedded in other DTOs.
class UserRelationDTO(TypedDict, total=False):
    id: str
    created_at: str
    updated_at: str
    role: Role
    avatar_url: str

# UserMetadataDTO is the API representation of user metadata.
class UserMetadataDTO(TypedDict, total=False):
    user_id: str
    completed_onboarding: bool
    use_case: str
    use_case_reason: str
    use_case_privacy: str
    signup_source: str
    terms_accepted_at: Optional[str]
    terms_version: str

# A2UIComponent is the universal component representation.
# Children are string IDs (flat adjacency list), not nested objects.
class A2UIComponent(TypedDict, total=False):
    id: str
    component: A2UIComponentType
    # Layout
    children: List[str]
    justify: str
    align: str
    direction: str
    gap: int
    # Text
    text: Optional[A2UIBoundValue]
    variant: str
    # Image
    url: Optional[A2UIBoundValue]
    fit: str
    # Icon
    name: Optional[A2UIBoundValue]
    # Divider
    axis: str
    # Button / Card
    child: str
    primary: bool
    action: Optional[A2UIAction]
    # TextField
    label: str
    value: Optional[A2UIBoundValue]
    textFieldType: str
    validationRegexp: str
    placeholder: str
    rows: int
    # Slider
    minValue: Optional[float]
    maxValue: Optional[float]
    # DateTimeInput
    enableDate: Optional[bool]
    enableTime: Optional[bool]
    # ChoicePicker
    options: List[A2UIChoiceOption]
    selections: Optional[A2UIBoundValue]
    maxAllowedSelections: Optional[int]
    # Modal
    entryPointChild: str
    contentChild: str
    # Tabs
    tabItems: List[A2UITabItem]
    # Common
    accessibility: Optional[A2UIAccessibility]
    weight: Optional[float]
    disabled: bool
    required: bool
    # Extension: Badge
    badgeLabel: str
    badgeVariant: str
    # Extension: Spacer
    minSize: Any
    # Extension: Chart
    chartData: Any
    chartSeries: Any
    xAxis: Any
    showYAxis: bool
    showLegend: bool
    showTooltip: bool
    # Extension: Form
    onSubmitAction: Optional[A2UIAction]
    # Extension: HTML
    htmlContent: str

# A2UIBoundValue is either a literal or a data model path reference.
class A2UIBoundValue(TypedDict, total=False):
    path: str

class A2UIAction(TypedDict, total=False):
    type: str
    payload: Any

class A2UIChoiceOption(TypedDict, total=False):
    label: str
    value: str

class A2UITabItem(TypedDict, total=False):
    title: str
    child: str

class A2UIAccessibility(TypedDict, total=False):
    label: str
    description: str

# A2UISurface is the complete renderable state for a widget.
class A2UISurface(TypedDict, total=False):
    version: str
    surfaceId: str
    catalogId: str
    components: List[A2UIComponent]
    dataModel: Any

# ChatData contains agent-specific data for a chat session
class ChatData(TypedDict, total=False):
    plan_steps: List[PlanStep]
    memory: StringEncodedMap
    always_allowed_tools: List[str]

# PlanStep represents a step in an agent's execution plan
class PlanStep(TypedDict, total=False):
    index: int
    title: str
    description: str
    notes: Optional[str]
    status: PlanStepStatus

# ChatMessageContent represents the content of a chat message
class ChatMessageContent(TypedDict, total=False):
    type: ChatMessageContentType
    error: Optional[str]
    text: Optional[str]
    image: Optional[str]
    file: Optional[str]
    tool_calls: Optional[List[ToolCall]]

# IntegrationContext holds integration-specific metadata for a chat
class IntegrationContext(TypedDict, total=False):
    integration_type: Optional[IntegrationType]
    integration_metadata: Any

StringEncodedMap = Dict[str, Any]

# FlowViewport represents the viewport state of a flow canvas
class FlowViewport(TypedDict, total=False):
    x: float
    y: float
    zoom: float

# FlowNode represents a node in a flow graph
class FlowNode(TypedDict, total=False):
    id: str
    type: str
    position: FlowNodePosition

# FlowNodePosition represents the position of a node
class FlowNodePosition(TypedDict, total=False):
    x: float
    y: float

# FlowEdge represents an edge between nodes in a flow graph
class FlowEdge(TypedDict, total=False):
    id: str
    type: str
    source: str
    target: str
    source_handle: Optional[str]
    target_handle: Optional[str]

# FlowNodeConnection represents a connection between nodes in a flow
class FlowNodeConnection(TypedDict, total=False):
    nodeId: str
    key: str
    type: str
    previousValue: Any

# FlowRunInputs maps node IDs to their input key-value pairs
FlowRunInputs = Dict[str, Dict[str, "FlowRunInput"]]

# FlowRunInput represents a single input value or connection for a flow node
class FlowRunInput(TypedDict, total=False):
    Connection: Optional[FlowNodeConnection]
    Value: Any

# OutputFieldMapping represents a mapping from a source node's field to an output field
class OutputFieldMapping(TypedDict, total=False):
    sourceNodeId: str
    sourceFieldPath: str
    outputFieldName: str
    type: str
    schema: Any

# OutputMappings is a map of output field name to OutputFieldMapping
OutputMappings = Dict[str, "OutputFieldMapping"]

# HookEventDefinition describes a lifecycle hook event and its capabilities.
class HookEventDefinition(TypedDict, total=False):
    event: HookEvent
    description: str
    can_gate: bool

# LLMOutput is the output envelope from an LLM provider task.
# This is the contract between chat apps (sdk-py) and the agent runtime (go/api).
class LLMOutput(TypedDict, total=False):
    response: str
    reasoning: Optional[str]
    tool_calls: Optional[List[ToolCall]]
    usage: Optional[LLMUsage]

# ModelSettings groups sampling and generation parameters as a passable unit.
class ModelSettings(TypedDict, total=False):
    temperature: Optional[float]
    top_p: Optional[float]
    top_k: Optional[int]
    min_p: Optional[float]
    frequency_penalty: Optional[float]
    presence_penalty: Optional[float]
    repetition_penalty: Optional[float]
    seed: Optional[int]
    stop: List[str]
    max_tokens: Optional[int]
    reasoning_effort: Optional[str]
    reasoning_max_tokens: Optional[int]

# LLMInput is the input envelope for an LLM provider task.
class LLMInput(TypedDict, total=False):
    model: Optional[str]
    context_size: int
    temperature: Optional[float]
    top_p: Optional[float]
    top_k: Optional[int]
    min_p: Optional[float]
    frequency_penalty: Optional[float]
    presence_penalty: Optional[float]
    repetition_penalty: Optional[float]
    seed: Optional[int]
    stop: List[str]
    max_tokens: Optional[int]
    reasoning_effort: Optional[str]
    reasoning_max_tokens: Optional[int]
    system_prompt: str
    context: List[LLMContextMessage]
    role: ChatMessageRole
    text: Optional[str]
    reasoning: Optional[str]
    attachments: Optional[List[FileRef]]
    images: Optional[List[str]]
    files: Optional[List[str]]
    tools: Optional[List[Tool]]
    tool_call_id: Optional[str]

# LLMContextMessage represents a message in the chat context for LLM tasks
class LLMContextMessage(TypedDict, total=False):
    role: ChatMessageRole
    text: Optional[str]
    reasoning: Optional[str]
    images: Optional[List[str]]
    files: Optional[List[str]]
    tools: Optional[List[Tool]]
    tool_calls: Optional[List[ToolCall]]
    tool_call_id: Optional[str]

# TaskAction defines an action to execute when a task reaches a specific status.
class TaskAction(TypedDict, total=False):
    key: str
    on: str
    params: Any

# TaskMetadata holds optional metadata attached to a task.
class TaskMetadata(TypedDict, total=False):
    action: Optional[TaskAction]

# ToolCall represents a tool call from an LLM response (wire format)
# This is a transport object for parsing LLM responses, not a database model
class ToolCall(TypedDict, total=False):
    id: str
    type: ToolCallType
    function: ToolCallFunction

# ToolCallFunction contains the function name and arguments from an LLM tool call
class ToolCallFunction(TypedDict, total=False):
    name: str
    arguments: StringEncodedMap

# LLMUsage contains token usage and performance metrics from an LLM response
class LLMUsage(TypedDict, total=False):
    stop_reason: str
    time_to_first_token: float
    tokens_per_second: float
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    reasoning_tokens: int
    reasoning_time: float

# FileRef is a lightweight reference to a file with essential metadata.
# Used in chat inputs/context instead of full File objects.
class FileRef(TypedDict, total=False):
    id: str
    uri: str
    filename: str
    content_type: str
    size: int

# Tool represents a tool definition for LLM function calling
class Tool(TypedDict, total=False):
    type: ToolCallType
    function: ToolFunction

class ToolFunction(TypedDict, total=False):
    name: str
    description: str
    parameters: ToolParameters
    required: Optional[List[str]]

class ToolParameters(TypedDict, total=False):
    type: ToolParamType
    title: str
    properties: ToolParameterProperties
    required: Optional[List[str]]

ToolParameterProperties = Dict[str, "ToolParameterProperty"]

class ToolParameterProperty(TypedDict, total=False):
    type: ToolParamType
    title: str
    description: str
    properties: Optional[ToolParameterProperties]
    items: Optional[ToolParameterProperty]
    required: Optional[List[str]]

# AppVersionDTO is the API response for an app version.
class AppVersionDTO(BaseModelDTO, TypedDict, total=False):
    metadata: Dict[str, Any]
    repository: str
    flow_version_id: Optional[str]
    flow_version: Optional[FlowVersionDTO]
    setup_schema: Any
    input_schema: Any
    output_schema: Any
    functions: Dict[str, AppFunction]
    default_function: str
    variants: Dict[str, AppVariant]
    env: Dict[str, str]
    kernel: str
    required_secrets: List[SecretRequirement]
    required_integrations: List[IntegrationRequirement]
    resources: AppResources
    checksum: str

# LicenseRecordDTO is the API response for a license record.
class LicenseRecordDTO(BaseModelDTO, TypedDict, total=False):
    user_id: str
    app_id: str
    license: str

# WorkerDTO is the full API response for a worker.
class WorkerDTO(BaseModelDTO, TypedDict, total=False):
    user_id: str
    team_id: str
    index: int
    status: WorkerStatus
    engine_id: str
    task_id: Optional[str]
    app_id: str
    app_version_id: str
    active_session_id: Optional[str]
    gpus: List[WorkerGPU]
    cpus: List[WorkerCPU]
    rams: List[WorkerRAM]
    system_info: SystemInfo
    warm_apps: List[str]

# EntitlementDTO for API responses
class EntitlementDTO(BaseModelDTO, TypedDict, total=False):
    team_id: str
    resource: EntitlementResource
    type: EntitlementType
    enabled: bool
    unlimited: bool
    limit: int
    source: EntitlementSource
    enforcement: EnforcementMode
    expires_at: Optional[str]
    team_plan_id: Optional[str]

# FlowVersionDTO for API responses
class FlowVersionDTO(BaseModelDTO, TypedDict, total=False):
    graph_version: int
    input_schema: Any
    input: FlowRunInputs
    output_schema: Any
    output_mappings: OutputMappings
    node_data: FlowNodeDataMap
    nodes: List[FlowNode]
    edges: List[FlowEdge]
    viewport: Optional[FlowViewport]

# GraphNodeDTO is the API representation of a graph node
class GraphNodeDTO(BaseModelDTO, TypedDict, total=False):
    graph_id: str
    type: GraphNodeType
    label: str
    resource_id: str
    resource_type: str
    status: GraphNodeStatus
    metadata: StringEncodedMap
    ready_at: Optional[str]
    started_at: Optional[str]
    completed_at: Optional[str]
    duration_ms: Optional[int]

# GraphEdgeDTO is the API representation of a graph edge
class GraphEdgeDTO(BaseModelDTO, TypedDict, total=False):
    type: GraphEdgeType
    from_node: str
    to_node: str

class SkillVersionDTO(BaseModelDTO, TypedDict, total=False):
    skill_id: str
    instructions: KnowledgeFile
    files: List[KnowledgeFile]
    content_hash: str
    description: str
    tags: List[str]
    allowed_tools: str
    compatibility: str
    license: str
    source_url: str
    mutation_type: str
    version_notes: str
    disable_model_invocation: bool
    user_invocable: Optional[bool]
    context: str
    metadata: Dict[str, str]

class KnowledgeVersionDTO(BaseModelDTO, TypedDict, total=False):
    knowledge_id: str
    content: KnowledgeFile
    files: List[KnowledgeFile]
    content_hash: str
    description: str
    tags: List[str]
    scope: List[str]
    metadata: Dict[str, str]
    source_url: str
    mutation_type: str
    version_notes: str
    last_confirmed_at: Optional[str]

# PlanDTO for API responses
class PlanDTO(BaseModelDTO, TypedDict, total=False):
    name: str
    description: str
    display_order: int
    active: bool
    self_serve: Optional[bool]
    plan_type: PlanType
    credits_monthly: int
    active_version: Optional[PlanVersionDTO]
    required_plan_ids: List[str]
    required_plan_names: List[str]
    stackable: bool
    limits: PlanLimits

class PlanVersionDTO(BaseModelDTO, TypedDict, total=False):
    plan_id: str
    amount_monthly: int
    amount_yearly: int
    provider_price_id_monthly: str
    provider_price_id_yearly: str
    credits_monthly: int
    limits: PlanLimits
    active: bool

# RefRouteDTO for API responses
class RefRouteDTO(BaseModelDTO, TypedDict, total=False):
    type: RefRouteType
    alias_ref: str
    target_ref: str
    primary: bool
    mode: RefRouteMode
    description: str
    enabled: bool

class ResourceShareDTO(BaseModelDTO, TypedDict, total=False):
    resource_id: str
    resource_type: str
    user_id: str
    user: Optional[UserRelationDTO]
    permission: Permission

# SubscriptionDTO for API responses
class SubscriptionDTO(BaseModelDTO, TypedDict, total=False):
    team_id: str
    plan_id: str
    plan: Optional[PlanDTO]
    interval: SubscriptionInterval
    status: SubscriptionStatus
    current_period_start: str
    current_period_end: str
    trial_end: Optional[str]
    cancel_at_period_end: bool
    credits_per_period: int

# UserDTO is the API response for a full user.
class UserDTO(BaseModelDTO, TypedDict, total=False):
    default_team_id: str
    role: Role
    email: str
    name: str
    full_name: str
    avatar_url: str
    banned_at: Optional[str]
    ban_note: str
    metadata: Optional[UserMetadataDTO]

class AgentVersionDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    description: str
    system_prompt: str
    example_prompts: List[str]
    core_app: Optional[CoreAppConfigDTO]
    tools: List[Optional[AgentToolDTO]]
    skills: List[SkillConfig]
    context: List[ContextField]
    internal_tools: Optional[InternalToolsConfig]
    hooks: List[LifecycleHookConfig]
    output_schema: Optional[Any]

class AgentRunDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    agent_id: str
    agent: Optional[AgentDTO]
    agent_version_id: Optional[str]
    chat_id: str
    user_message_id: Optional[str]
    state: AgentRunState
    error: Optional[str]
    output: Optional[Any]
    interrupt_reason: Optional[InterruptReason]
    interrupt_tool_id: Optional[str]
    interrupt_meta: Any
    tool_invocation_id: Optional[str]
    trigger_id: Optional[str]
    metadata: Any

# ApiKeyDTO for API responses
class ApiKeyDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    name: str
    key: str
    last_used_at: str
    expires_at: Optional[str]
    scopes: List[Scope]
    source: str

# AppDTO is the API response for a full app.
class AppDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    namespace: str
    name: str
    description: str
    agent_description: str
    category: AppCategory
    images: AppImages
    version_id: str
    version: Optional[AppVersionDTO]
    status: AppStatus
    status_message: str
    status_changed_at: Optional[str]

# AppSessionDTO is the external representation
class AppSessionDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    worker_id: str
    app_id: str
    app_version_id: str
    status: AppSessionStatus
    expires_at: str
    ended_at: Optional[str]
    task_id: Optional[str]
    call_count: int
    last_call_at: Optional[str]
    idle_timeout: Optional[int]

# BountyProgramDTO is the API representation of a bounty program.
class BountyProgramDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    name: str
    description: str
    amount_microcents: int
    grant_type: str
    expiry_days: int
    max_per_user: int
    max_per_day: int
    proof_type: str
    proof_min_length: int
    status: str
    notice_text: str
    notice_cooldown_hours: int
    notice_priority: int
    starts_at: Optional[str]
    ends_at: Optional[str]

# BountySubmissionDTO is the API representation of a bounty claim.
class BountySubmissionDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    bounty_id: str
    resource_id: str
    proof_id: str
    proof_ref: str
    agent: str
    source: str

# ChatDTO for API responses
class ChatDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    parent_id: Optional[str]
    parent: Optional[ChatDTO]
    children: List[Optional[ChatDTO]]
    status: ChatStatus
    output: Optional[Any]
    context: Dict[str, str]
    agent_id: Optional[str]
    agent: Optional[AgentDTO]
    agent_version_id: Optional[str]
    agent_version: Optional[AgentVersionDTO]
    name: str
    description: str
    chat_messages: List[ChatMessageDTO]
    agent_data: ChatData
    active_run: Optional[AgentRunDTO]

# ChatMessageDTO for API responses
class ChatMessageDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    chat_id: str
    chat: Optional[ChatDTO]
    agent_run_id: Optional[str]
    order: int
    status: ChatMessageStatus
    task_id: Optional[str]
    role: ChatMessageRole
    content: List[ChatMessageContent]
    tools: Optional[List[Tool]]
    tool_call_id: Optional[str]
    tool_invocations: Optional[List[ToolInvocationDTO]]

# EngineDTO is the full API response for an engine.
class EngineDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    instance: Optional[InstanceDTO]
    config: EngineConfig
    name: str
    api_url: str
    status: EngineStatus
    engine_version: str
    system_info: Optional[SystemInfo]
    workers: List[Optional[WorkerDTO]]

# EngineSummary is a lightweight engine response embedded in tasks.
class EngineSummary(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    instance: Optional[InstanceDTO]
    name: str
    status: EngineStatus
    workers: List[Optional[WorkerSummary]]

# FileDTO for API responses
class FileDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    path: str
    remote_path: str
    upload_url: str
    uri: str
    content_type: str
    size: int
    filename: str
    category: str
    rating: ContentRating
    metadata: Optional[FileMetadata]

# FlowDTO for API responses
class FlowDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    namespace: str
    name: str
    description: str
    card_image: str
    thumbnail: str
    banner_image: str
    draft_version_id: str
    draft_version: Optional[FlowVersionDTO]
    published_version_id: str
    published_version: Optional[FlowVersionDTO]
    input_schema: Any
    input: FlowRunInputs
    output_schema: Any
    output_mappings: OutputMappings
    node_data: FlowNodeDataMap
    nodes: List[FlowNode]
    edges: List[FlowEdge]
    viewport: Optional[FlowViewport]

# FlowRunDTO for API responses
class FlowRunDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    flow_id: str
    flow_version_id: str
    flow_version: Optional[FlowVersionDTO]
    task_id: Optional[str]
    status: FlowRunStatus
    error: Optional[str]
    flow_run_started: Optional[str]
    flow_run_finished: Optional[str]
    flow_run_cancelled: Optional[str]
    input: FlowRunInputs
    fail_on_error: bool
    output: Any
    node_tasks: Dict[str, Optional[NodeTaskDTO]]

# InstanceDTO is the API representation of a cloud instance.
class InstanceDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    cloud: InstanceCloudProvider
    name: str
    region: str
    shade_cloud: bool
    shade_instance_type: str
    cloud_instance_type: str
    cloud_assigned_id: str
    os: str
    ssh_key_id: str
    ssh_user: str
    ssh_port: int
    ip: str
    status: InstanceStatus
    cost_estimate: str
    hourly_price: int
    template_id: str
    volume_ids: List[str]
    tags: List[str]
    configuration: Any
    launch_configuration: Any
    auto_delete: Any
    alert: Any
    volume_mount: Any
    envs: Any

# InstanceTypeDTO is the API representation of a cloud instance type.
class InstanceTypeDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    cloud: InstanceCloudProvider
    cloud_logo_url: str
    region: str
    shade_instance_type: str
    cloud_instance_type: str
    deployment_type: InstanceTypeDeploymentType
    hourly_price: int
    configuration: Optional[InstanceTypeConfiguration]
    availability: List[InstanceTypeAvailability]
    boot_time: Optional[InstanceTypeBootTime]

# IntegrationDTO for API responses (never exposes tokens)
class IntegrationDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    scope: IntegrationScope
    grant: Optional[IntegrationGrant]
    provider: IntegrationProvider
    type: IntegrationAuthType
    auth: IntegrationAuthType
    status: IntegrationStatus
    display_name: str
    icon_url: str
    scopes: StringSlice
    expires_at: Optional[str]
    service_account_email: str
    metadata: Dict[str, Any]
    account_identifier: str
    account_name: str
    is_primary: bool
    error_message: str

class InterruptDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    run_id: str
    chat_id: str
    reason: InterruptReason
    source: str
    resource_id: str
    resource_type: InterruptResourceType
    status: InterruptStatus
    resolution: Optional[InterruptResolution]
    resolved_at: Optional[str]
    resolved_data: Any
    expires_at: Optional[str]
    meta: Any

# SkillDTO for API responses (backward-compatible naming)
class SkillDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    namespace: str
    name: str
    description: str
    repo_url: str
    version_id: str
    version: Optional[SkillVersionDTO]
    uses: int
    installs: int

# KnowledgeDTO — generic DTO for /knowledge endpoints (all types)
class KnowledgeDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    namespace: str
    name: str
    description: str
    type: KnowledgeType
    lifecycle: KnowledgeLifecycle
    version_id: str
    version: Optional[KnowledgeVersionDTO]
    uses: int
    installs: int

# NotificationDTO is the data transfer object
class NotificationDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    type: NotificationType
    channel: NotificationChannel
    priority: NotificationPriority
    status: NotificationStatus
    recipient_email: str
    subject: str
    body: str
    scheduled_at: Optional[str]
    sent_at: Optional[str]
    delivered_at: Optional[str]
    failed_at: Optional[str]
    error_message: str
    retry_count: int
    reference_type: str
    reference_id: str

# NotificationPreferencesDTO is the data transfer object
class NotificationPreferencesDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    email_enabled: bool
    sms_enabled: bool
    push_enabled: bool
    slack_enabled: bool
    billing_notifications: bool
    task_notifications: bool
    system_notifications: bool
    marketing_emails: bool
    quiet_hours_enabled: bool
    quiet_hours_start: str
    quiet_hours_end: str
    timezone: str

# PageDTO for API responses
class PageDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    is_featured: bool
    title: str
    content: str
    excerpt: str
    status: PageStatus
    type: PageType
    metadata: PageMetadata
    slug: str
    # PublishAt mirrors Metadata.PublishAt, which remains the field clients write.
    # Surfaced here so a reader does not have to reach into the metadata blob.
    publish_at: Optional[str]

# MenuDTO for API responses
class MenuDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    name: str
    slug: str
    description: str
    items: List[MenuItem]

# ProjectDTO for API responses
class ProjectDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    name: str
    description: str
    type: ProjectType
    color: Optional[str]
    icon: Optional[str]
    parent_id: Optional[str]
    parent: Optional[ProjectDTO]
    children: List[Optional[ProjectDTO]]

# SecretDTO for API responses - VALUE IS NEVER EXPOSED
class SecretDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    key: str
    masked_value: str
    description: str
    scope: SecretScope

# TaskDTO is the full API response for a task.
class TaskDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    graph_id: Optional[str]
    user_public_key: bytes
    engine_public_key: bytes
    is_featured: bool
    status: TaskStatus
    app_id: str
    app: Optional[AppDTO]
    app_version_id: str
    app_version: Optional[AppVersionDTO]
    app_variant: str
    function: str
    infra: Infra
    workers: List[str]
    flow_run_id: Optional[str]
    chat_id: Optional[str]
    sub_flow_run_id: Optional[str]
    agent_id: Optional[str]
    agent_version_id: Optional[str]
    agent: Optional[AgentDTO]
    engine_id: Optional[str]
    engine: Optional[EngineSummary]
    worker_id: Optional[str]
    worker: Optional[WorkerSummary]
    run_at: Optional[str]
    webhook: Optional[str]
    setup: Optional[Any]
    input: Any
    output: Any
    error: Optional[str]
    rating: ContentRating
    events: List[TaskEvent]
    logs: List[TaskLog]
    usage_events: List[Optional[UsageEventDTO]]
    session_id: Optional[str]
    session_timeout: Optional[int]

# ToolInvocationDTO for API responses
class ToolInvocationDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    chat_message_id: str
    tool_invocation_id: str
    type: ToolType
    display_name: str
    execution_id: Optional[str]
    function: ToolInvocationFunction
    status: ToolInvocationStatus
    result: Optional[str]
    data: Optional[Any]
    widget: Optional[Widget]

# UsageEventDTO is the API representation of a usage event.
class UsageEventDTO(BaseModelDTO, PermissionModelDTO, TypedDict, total=False):
    usage_billing_record_id: str
    reference_id: str
    resource_id: str
    tier: UsageEventResourceTier
    type: str
    model: str
    quantity: int
    unit: str

# AgentDTO for API responses
class AgentDTO(BaseModelDTO, PermissionModelDTO, ProjectModelDTO, TypedDict, total=False):
    namespace: str
    name: str
    images: AgentImages
    version_id: str
    version: Optional[AgentVersionDTO]

# Widget is an A2UI surface stored on a ToolInvocation.
# Alias of shared.A2UISurface so the type generation pipeline picks it up.
Widget = A2UISurface

# API Key Scopes - hierarchical permission system.
# Resource-level scopes (e.g., "agents") imply all action-level scopes (e.g., "agents:read").
# Empty scopes = full access (for backwards compatibility with existing keys).
class Scope(str, Enum):
    ALL = "*"
    # Resource-level scopes (implies all actions)
    AGENTS = "agents"
    APPS = "apps"
    CONVERSATIONS = "conversations"
    FILES = "files"
    DATASTORES = "datastores"
    TEMPLATES = "templates"
    FLOWS = "flows"
    PROJECTS = "projects"
    TEAMS = "teams"
    BILLING = "billing"
    # Action-level scopes for Agents
    AGENTS_READ = "agents:read"
    AGENTS_WRITE = "agents:write"
    AGENTS_EXECUTE = "agents:execute"
    # Action-level scopes for Apps
    APPS_READ = "apps:read"
    APPS_WRITE = "apps:write"
    APPS_EXECUTE = "apps:execute"
    # Action-level scopes for Conversations/Chats
    CONVERSATIONS_READ = "conversations:read"
    CONVERSATIONS_WRITE = "conversations:write"
    # Action-level scopes for Files
    FILES_READ = "files:read"
    FILES_WRITE = "files:write"
    # Action-level scopes for Datastores
    DATASTORES_READ = "datastores:read"
    DATASTORES_WRITE = "datastores:write"
    # Action-level scopes for Flows
    FLOWS_READ = "flows:read"
    FLOWS_WRITE = "flows:write"
    FLOWS_EXECUTE = "flows:execute"
    # Action-level scopes for Projects
    PROJECTS_READ = "projects:read"
    PROJECTS_WRITE = "projects:write"
    # Action-level scopes for Teams
    TEAMS_READ = "teams:read"
    TEAMS_WRITE = "teams:write"
    # Action-level scopes for Billing
    BILLING_READ = "billing:read"
    BILLING_WRITE = "billing:write"
    # Action-level scopes for Secrets (sensitive - excluded from read-only preset)
    SECRETS_READ = "secrets:read"
    SECRETS_WRITE = "secrets:write"
    # Action-level scopes for Integrations
    INTEGRATIONS_READ = "integrations:read"
    INTEGRATIONS_WRITE = "integrations:write"
    # Action-level scopes for Engines
    ENGINES_READ = "engines:read"
    ENGINES_WRITE = "engines:write"
    # Action-level scopes for API Keys
    API_KEYS_READ = "apikeys:read"
    API_KEYS_WRITE = "apikeys:write"
    # Action-level scopes for User profile
    USER_READ = "user:read"
    USER_WRITE = "user:write"
    # Action-level scopes for Settings/Notifications
    SETTINGS_READ = "settings:read"
    SETTINGS_WRITE = "settings:write"

class ScopeGroup(str, Enum):
    AGENTS = "agents"
    APPS = "apps"
    CONVERSATIONS = "conversations"
    FILES = "files"
    DATASTORES = "datastores"
    FLOWS = "flows"
    PROJECTS = "projects"
    TEAMS = "teams"
    BILLING = "billing"
    SECRETS = "secrets"
    INTEGRATIONS = "integrations"
    ENGINES = "engines"
    API_KEYS = "apikeys"
    USER = "user"
    SETTINGS = "settings"

# Flow graph action type constants.
class FlowActionType(str, Enum):
    ACTION_NODE_ADD = "node.add"
    ACTION_NODE_REMOVE = "node.remove"
    ACTION_NODE_MOVE = "node.move"
    ACTION_NODE_MOVE_MANY = "node.move_many"
    ACTION_NODE_DUPLICATE = "node.duplicate"
    ACTION_NODE_RENAME = "node.rename"
    ACTION_NODE_SET_APP = "node.set_app"
    ACTION_NODE_UPDATE = "node.update"
    ACTION_NODE_SET_INPUT = "node.set_input"
    ACTION_NODE_CLEAR_INPUT = "node.clear_input"
    ACTION_EDGE_ADD = "edge.add"
    ACTION_EDGE_REMOVE = "edge.remove"
    ACTION_FLOW_SET_INPUT_SCHEMA = "flow.set_input_schema"
    ACTION_FLOW_SET_OUTPUT_SCHEMA = "flow.set_output_schema"
    ACTION_FLOW_SET_OUTPUT_MAPPING = "flow.set_output_mapping"
    ACTION_FLOW_REMOVE_OUTPUT_MAPPING = "flow.remove_output_mapping"
    ACTION_FLOW_RENAME_OUTPUT_FIELD = "flow.rename_output_field"

class ElicitAction(str, Enum):
    ACCEPT = "accept"
    DECLINE = "decline"
    CANCEL = "cancel"

class ResultType(str, Enum):
    # ResultTypeComplete marks an ordinary, finished result.
    COMPLETE = "complete"
    # ResultTypeInputRequired marks a Multi Round-Trip Request interim result.
    # Recognised so the outbound client never mistakes one for tool output.
    INPUT_REQUIRED = "input_required"

class CacheScope(str, Enum):
    # CacheScopePublic marks a response as free of user-specific data, so any
    # client or shared intermediary may cache it across authorization contexts.
    PUBLIC = "public"
    # CacheScopePrivate restricts reuse to the same authorization context.
    PRIVATE = "private"

class ToolContentType(str, Enum):
    TEXT = "text"
    IMAGE = "image"
    AUDIO = "audio"
    RESOURCE_LINK = "resource_link"
    RESOURCE = "resource"

# Requirement error types
class RequirementType(str, Enum):
    SECRET = "secret"
    INTEGRATION = "integration"
    SCOPE = "scope"

class SetupActionType(str, Enum):
    SETUP_ACTION_ADD_SECRET = "add_secret"
    SETUP_ACTION_CONNECT = "connect"
    SETUP_ACTION_ADD_SCOPES = "add_scopes"

class A2UIComponentType(str, Enum):
    A2UI_ROW = "Row"
    A2UI_COLUMN = "Column"
    A2UI_LIST = "List"
    A2UI_TEXT = "Text"
    A2UI_IMAGE = "Image"
    A2UI_ICON = "Icon"
    A2UI_DIVIDER = "Divider"
    A2UI_BUTTON = "Button"
    A2UI_TEXT_FIELD = "TextField"
    A2UI_CHECK_BOX = "CheckBox"
    A2UI_SLIDER = "Slider"
    A2UI_DATE_TIME_INPUT = "DateTimeInput"
    A2UI_CHOICE_PICKER = "ChoicePicker"
    A2UI_CARD = "Card"
    A2UI_MODAL = "Modal"
    A2UI_TABS = "Tabs"
    # Extensions (inferencesh/v1 catalog)
    A2UI_BADGE = "Badge"
    A2UI_SPACER = "Spacer"
    A2UI_CHART = "Chart"
    A2UI_FORM = "Form"
    A2UIHTML = "HTML"

class AgentRunState(str, Enum):
    SUBMITTED = "submitted"
    WORKING = "working"
    INPUT_REQUIRED = "input_required"
    AUTH_REQUIRED = "auth_required"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELED = "canceled"
    REJECTED = "rejected"

class InterruptReason(str, Enum):
    TOOL_APPROVAL = "tool_approval"
    CLIENT_TOOL = "client_tool"
    WIDGET = "widget"
    AUTH = "auth"
    CONFIRMATION = "confirmation"
    HOOK_GATE = "hook_gate"

class AppCategory(str, Enum):
    IMAGE = "image"
    VIDEO = "video"
    AUDIO = "audio"
    TEXT = "text"
    CHAT = "chat"
    _3D = "3d"
    OTHER = "other"
    FLOW = "flow"

class AppStatus(str, Enum):
    ACTIVE = "active"
    MAINTENANCE = "maintenance"
    DEPRECATED = "deprecated"
    RETIRED = "retired"

class GPUType(str, Enum):
    ANY = "any"
    NONE = "none"
    INTEL = "intel"
    NVIDIA = "nvidia"
    AMD = "amd"
    APPLE = "apple"

class Visibility(str, Enum):
    PRIVATE = "private"
    TEAM = "team"
    PUBLIC = "public"
    UNLISTED = "unlisted"

class Permission(str, Enum):
    PERM_READ = "read"
    PERM_WRITE = "write"

class SubscriptionStatus(str, Enum):
    TRIALING = "trialing"
    ACTIVE = "active"
    PAST_DUE = "past_due"
    CANCELED = "canceled"
    PAUSED = "paused"

class SubscriptionInterval(str, Enum):
    MONTHLY = "monthly"
    YEARLY = "yearly"

class PlanType(str, Enum):
    BASE = "base"
    ADDON = "addon"

class EntitlementSource(str, Enum):
    TIER = "tier"
    OVERRIDE = "override"
    WHITELIST = "whitelist"
    TRIAL = "trial"
    ADDON = "addon"

class EntitlementType(str, Enum):
    BOOLEAN = "boolean"
    LIMIT = "limit"

class EnforcementMode(str, Enum):
    ENFORCEMENT_BLOCK = "block"
    ENFORCEMENT_WARN = "warn"

class ChatStatus(str, Enum):
    BUSY = "busy"
    IDLE = "idle"
    AWAITING_INPUT = "awaiting_input"
    COMPLETED = "completed"

class PlanStepStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"

class ChatMessageRole(str, Enum):
    # LLM wire-protocol roles
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"
    # Internal bookkeeping roles — never sent to the LLM provider.
    # BuildContext converts these to system messages or skips them.
    INJECTION = "injection"
    COMPACTION = "compaction"

class ChatMessageStatus(str, Enum):
    PENDING = "pending"
    QUEUED = "queued"
    READY = "ready"
    FAILED = "failed"
    CANCELLED = "cancelled"

class ChatMessageContentType(str, Enum):
    TEXT = "text"
    REASONING = "reasoning"
    IMAGE = "image"
    FILE = "file"
    TOOL = "tool"

class IntegrationType(str, Enum):
    SLACK = "slack"
    DISCORD = "discord"
    TEAMS = "teams"
    TELEGRAM = "telegram"

class EngineStatus(str, Enum):
    RUNNING = "running"
    PENDING = "pending"
    DRAINING = "draining"
    DISCONNECTED = "disconnected"
    RESTARTING = "restarting"
    STOPPING = "stopping"
    STOPPED = "stopped"

class WorkerStatus(str, Enum):
    RESERVED = "reserved"
    BUSY = "busy"
    IDLE = "idle"
    INACTIVE = "inactive"

class FlowRunStatus(IntEnum):
    UNKNOWN = 0
    PENDING = 1
    RUNNING = 2
    COMPLETED = 3
    FAILED = 4
    CANCELLED = 5

class GraphNodeType(str, Enum):
    UNKNOWN = "unknown"
    JOIN = "join"
    SPLIT = "split"
    EXECUTION = "execution"
    RESOURCE = "resource"
    APPROVAL = "approval"
    CONDITIONAL = "conditional"
    FLOW_NODE = "flow_node"
    TRIGGER = "trigger"
    INTEGRATION_REQUIREMENT = "integration_requirement"

class GraphNodeStatus(str, Enum):
    PENDING = "pending"
    READY = "ready"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    SKIPPED = "skipped"
    BLOCKED = "blocked"

class ResourceType(str, Enum):
    KNOWLEDGE = "knowledge"
    APP = "app"
    AGENT = "agent"

class GraphEdgeType(str, Enum):
    DEPENDENCY = "dependency"
    FLOW = "flow"
    CONDITIONAL = "conditional"
    EXECUTION = "execution"
    PARENT = "parent"
    ANCESTOR = "ancestor"
    DUPLICATE = "duplicate"
    REFERENCES = "references"
    SUPERSEDES = "supersedes"
    INPUT = "input"
    OUTPUT = "output"

class InterruptStatus(str, Enum):
    PENDING = "pending"
    RESOLVED = "resolved"
    EXPIRED = "expired"
    CANCELLED = "cancelled"

class InterruptResolution(str, Enum):
    ALLOW = "allow"
    DENY = "deny"

class InterruptResourceType(str, Enum):
    INTERRUPT_RESOURCE_TOOL_INVOCATION = "tool_invocation"
    INTERRUPT_RESOURCE_HOOK_EVENT = "hook_event"

class HookEvent(str, Enum):
    AGENT_START = "agent.start"
    TURN_START = "agent.turn_start"
    TOOL_CALL = "agent.tool_call"
    TOOL_RESULT = "agent.tool_result"
    TURN_COMPLETE = "agent.turn_complete"
    AGENT_ERROR = "agent.error"
    AGENT_COMPLETE = "agent.complete"
    AGENT_IDLE = "agent.idle"
    PRE_COMPACT = "agent.pre_compact"
    POST_COMPACT = "agent.post_compact"

class HookDecision(str, Enum):
    ALLOW = "allow"
    DENY = "deny"
    STOP = "stop"
    SUSPEND = "suspend"

class HookHandlerType(str, Enum):
    HOOK_HANDLER_WEBHOOK = "webhook"
    HOOK_HANDLER_TASK = "task"
    HOOK_HANDLER_GATE = "gate"

class SecretScope(str, Enum):
    # SecretScopeTeam is a normal user secret, visible in team secret lists
    TEAM = "team"
    # SecretScopeInternal is an integration-managed secret, hidden from user lists
    INTERNAL = "internal"
    # SecretScopeSystem is a global system setting, owned by system team, admin-only
    SYSTEM = "system"

class PageStatus(IntEnum):
    UNKNOWN = 0
    DRAFT = 1
    PUBLISHED = 2
    ARCHIVED = 3
    SCHEDULED = 4

class PageType(str, Enum):
    DOC = "doc"
    BLOG = "blog"
    PAGE = "page"
    ANNOUNCEMENT = "announcement"

class ToolInvocationStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    AWAITING_INPUT = "awaiting_input"
    AWAITING_APPROVAL = "awaiting_approval"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"

class ToolType(str, Enum):
    APP = "app"
    AGENT = "agent"
    HOOK = "hook"
    HTTP = "http"
    CALL = "call"
    MCP = "mcp"
    CLIENT = "client"
    INTERNAL = "internal"

class InstanceCloudProvider(str, Enum):
    CLOUD_AWS = "aws"
    CLOUD_AMAYA = "amaya"
    CLOUD_AZURE = "azure"
    CLOUD_BOOSTRUN = "boostrun"
    CLOUD_CRUSOE = "crusoe"
    CLOUD_DATACRUNCH = "datacrunch"
    CLOUD_DENVR = "denvr"
    CLOUD_DIGITAL_OCEAN = "digitalocean"
    CLOUD_EXCESS_SUPPLY = "excesssupply"
    CLOUD_HORIZON = "horizon"
    CLOUD_HYPERSTACK = "hyperstack"
    CLOUD_IMWT = "imwt"
    CLOUD_JARVIS_LABS = "jarvislabs"
    CLOUD_LAMBDA_LABS = "lambdalabs"
    CLOUD_LATITUDE = "latitude"
    CLOUD_MASSED_COMPUTE = "massedcompute"
    CLOUD_NEBIUS = "nebius"
    CLOUD_OBLIVUS = "oblivus"
    CLOUD_PAPERSPACE = "paperspace"
    CLOUD_PHYNTEC = "phyntec"
    CLOUD_RUN_POD = "runpod"
    CLOUD_SCALEWAY = "scaleway"
    CLOUD_SHADE = "shade"
    CLOUD_TENSOR_DOCK = "tensordock"
    CLOUD_VERDA = "verda"
    CLOUD_VOLTAGE_PARK = "voltagepark"
    CLOUD_VULTR = "vultr"

class InstanceStatus(str, Enum):
    CREATING = "creating"
    PENDING_PROVIDER = "pending_provider"
    PENDING = "pending"
    ACTIVE = "active"
    ERROR = "error"
    DELETING = "deleting"
    DELETED = "deleted"

class InstanceTypeDeploymentType(str, Enum):
    VM = "vm"
    CONTAINER = "container"
    BAREMETAL = "baremetal"

class AppSessionStatus(str, Enum):
    ACTIVE = "active"
    ENDED = "ended"
    EXPIRED = "expired"

class ProjectType(str, Enum):
    AGENT = "agent"
    APP = "app"
    FLOW = "flow"
    OTHER = "other"

class UsageEventResourceTier(str, Enum):
    PRIVATE = "private"
    CLOUD = "cloud"

class MetaItemType(str, Enum):
    TEXT = "text"
    IMAGE = "image"
    VIDEO = "video"
    AUDIO = "audio"
    RAW = "raw"

class VideoResolution(str, Enum):
    VIDEO_RES480P = "480p"
    VIDEO_RES720P = "720p"
    VIDEO_RES1080P = "1080p"
    VIDEO_RES1440P = "1440p"
    VIDEO_RES4K = "4k"

class MCPServerAuthType(str, Enum):
    MCP_SERVER_AUTH_O_AUTH = "oauth"
    MCP_SERVER_AUTH_API_KEY = "api_key"
    MCP_SERVER_AUTH_NONE = "none"

class TeamInviteStatus(str, Enum):
    PENDING = "pending"
    ACCEPTED = "accepted"
    DECLINED = "declined"
    EXPIRED = "expired"
    REVOKED = "revoked"

class RefRouteType(str, Enum):
    APP = "app"
    AGENT = "agent"
    SKILL = "skill"

class RefRouteMode(str, Enum):
    REWRITE = "rewrite"
    REDIRECT = "redirect"

class KnowledgeType(str, Enum):
    CONCEPT = "concept"
    SKILL = "skill"
    OBSERVATION = "observation"
    PREFERENCE = "preference"
    REFERENCE = "reference"
    PERSON = "person"
    PROJECT = "project"
    AGENT_CONFIG = "agent-config"

class KnowledgeLifecycle(str, Enum):
    PERMANENT = "permanent"
    DECAY = "decay"

class FilterOperator(str, Enum):
    OP_EQUAL = "eq"
    OP_NOT_EQUAL = "neq"
    OP_IN = "in"
    OP_NOT_IN = "not_in"
    OP_GREATER = "gt"
    OP_GREATER_EQUAL = "gte"
    OP_LESS = "lt"
    OP_LESS_EQUAL = "lte"
    OP_LIKE = "like"
    OP_I_LIKE = "ilike"
    OP_CONTAINS = "contains"
    OP_NOT_CONTAINS = "not_contains"
    OP_IS_NULL = "is_null"
    OP_IS_NOT_NULL = "is_not_null"
    OP_IS_EMPTY = "is_empty"
    OP_IS_NOT_EMPTY = "is_not_empty"

class DeviceAuthStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    EXPIRED = "expired"
    DENIED = "denied"
    VALID = "valid"
    INVALID = "invalid"
    LOADING = "loading"

class DeviceTokenKind(str, Enum):
    # DeviceTokenKindSession mints a revocable CLI session (acts as the user,
    # supports team switching via X-Team-ID).
    SESSION = "session"
    # DeviceTokenKindAPIKey mints a device-scoped API key.
    # TODO: retire once CLIs older than the session-token release are gone.
    API_KEY = "api_key"

class EntitlementResource(str, Enum):
    # Capacity limits — scale with tier
    RESOURCE_API_KEYS = "api_keys"
    RESOURCE_CONNECTORS = "connectors"
    RESOURCE_KNOWLEDGE_BASES = "knowledge_bases"
    RESOURCE_STORAGE_MB = "storage_mb"
    RESOURCE_CONCURRENCY = "concurrency"
    RESOURCE_RATE_PER_MIN = "rate_per_min"
    RESOURCE_SEATS = "seats"
    RESOURCE_TRIGGERS = "triggers"
    RESOURCE_RETENTION_DAYS = "retention_days"
    # Legacy — kept for DB compatibility, no longer in plan seeds
    RESOURCE_PRIVATE_APPS = "private_apps"
    RESOURCE_TASK_EXECUTIONS = "task_executions"
    # Feature gates — only what has real cost/complexity
    RESOURCE_FEATURE_BYOK = "feature:byok"
    RESOURCE_FEATURE_SEEDANCE = "feature:seedance"
    # Legacy feature gates — kept for DB compatibility, no longer gated
    RESOURCE_FEATURE_SCOPES = "feature:scopes"
    RESOURCE_FEATURE_WEBHOOKS = "feature:webhooks"
    RESOURCE_FEATURE_TEAM_BILLING = "feature:team_billing"
    RESOURCE_FEATURE_AUTO_RECHARGE = "feature:auto_recharge"
    RESOURCE_FEATURE_INVOICES = "feature:invoices"
    RESOURCE_FEATURE_PUBLISH_APPS = "feature:publish_apps"

class ContentRating(str, Enum):
    CONTENT_SAFE = "safe"
    CONTENT_SEXUAL_SUGGESTIVE = "sexual_suggestive"
    CONTENT_SEXUAL_EXPLICIT = "sexual_explicit"
    CONTENT_VIOLENCE_NON_GRAPHIC = "violence_non_graphic"
    CONTENT_VIOLENCE_GRAPHIC = "violence_graphic"
    CONTENT_GORE = "gore"
    CONTENT_UNRATED = "unrated"

class IntegrationProvider(str, Enum):
    GOOGLE = "google"
    GOOGLE_SA = "google-sa"
    SLACK = "slack"
    NOTION = "notion"
    GIT_HUB = "github"
    X = "x"
    MICROSOFT = "microsoft"
    SALESFORCE = "salesforce"
    DISCORD = "discord"
    GCP = "gcp"
    MCP = "mcp"
    REDDIT = "reddit"

class IntegrationAuthType(str, Enum):
    SERVICE_ACCOUNT = "service_account"
    O_AUTH = "oauth"
    API_KEY = "api_key"
    WIF = "wif"
    MCP = "mcp"

class IntegrationStatus(str, Enum):
    PENDING = "pending"
    CONNECTED = "connected"
    DISCONNECTED = "disconnected"
    EXPIRED = "expired"
    ERROR = "error"

class IntegrationScope(str, Enum):
    TEAM = "team"
    PLATFORM = "platform"
    USER = "user"

class IntegrationGrant(str, Enum):
    # IntegrationGrantCredentials provides OAuth app credentials (client_id/secret).
    # Users connect their own accounts against it. Only valid for type=oauth.
    CREDENTIALS = "credentials"
    # IntegrationGrantToken provides ready-to-use access (token, API key, etc.).
    TOKEN = "token"

class NotificationChannel(str, Enum):
    EMAIL = "email"
    SMS = "sms"
    PUSH = "push"
    SLACK = "slack"

class NotificationPriority(str, Enum):
    LOW = "low"
    NORMAL = "normal"
    HIGH = "high"
    CRITICAL = "critical"

class NotificationType(str, Enum):
    # Billing notifications
    LOW_BALANCE = "low_balance"
    AUTO_RECHARGE = "auto_recharge"
    PAYMENT_SUCCESS = "payment_success"
    PAYMENT_FAILED = "payment_failed"
    USAGE_SUMMARY = "usage_summary"
    SPENDING_LIMIT = "spending_limit"
    INVOICE = "invoice"
    SUBSCRIPTION_CREATED = "subscription_created"
    SUBSCRIPTION_CREDIT = "subscription_credit"
    SUBSCRIPTION_CANCELED = "subscription_canceled"
    SUBSCRIPTION_PAYMENT_FAILED = "subscription_payment_failed"
    SUBSCRIPTION_TRIAL_ENDING = "subscription_trial_ending"
    # Account notifications
    WELCOME = "welcome"
    WELCOME_AGENTS = "welcome_agents"
    WELCOME_APPS = "welcome_apps"
    WELCOME_FLOWS = "welcome_flows"
    WELCOME_SDK = "welcome_sdk"
    PASSWORD_RESET = "password_reset"
    EMAIL_VERIFY = "email_verify"
    SECURITY_ALERT = "security_alert"
    # Task notifications
    TASK_COMPLETE = "task_complete"
    TASK_FAILED = "task_failed"
    # Data export
    DATA_EXPORT = "data_export"
    # System notifications
    SYSTEM_ALERT = "system_alert"
    MAINTENANCE = "maintenance"
    TOS_UPDATE = "tos_update"
    SERVICE_NOTICE = "service_notice"
    # Team notifications
    TEAM_INVITE = "team_invite"

class NotificationStatus(str, Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    SENT = "sent"
    DELIVERED = "delivered"
    FAILED = "failed"
    BOUNCED = "bounced"
    CANCELLED = "cancelled"

class TaskStatus(IntEnum):
    UNKNOWN = 0
    RECEIVED = 1
    QUEUED = 2
    DISPATCHED = 3
    PREPARING = 4
    SERVING = 5
    SETTING_UP = 6
    RUNNING = 7
    CANCELLING = 8
    UPLOADING = 9
    COMPLETED = 10
    FAILED = 11
    CANCELLED = 12

class Infra(str, Enum):
    PRIVATE = "private"
    CLOUD = "cloud"
    PRIVATE_FIRST = "private_first"

class TaskLogType(IntEnum):
    BUILD = 0
    RUN = 1
    SERVE = 2
    SETUP = 3
    TASK = 4

class TeamType(str, Enum):
    PERSONAL = "personal"
    TEAM = "team"
    SYSTEM = "system"

class TeamStatus(str, Enum):
    ACTIVE = "active"
    SUSPENDED = "suspended"
    TERMINATED = "terminated"

class TeamRole(str, Enum):
    OWNER = "owner"
    ADMIN = "admin"
    MEMBER = "member"

# Tool call types
class ToolCallType(str, Enum):
    TOOL_TYPE_FUNCTION = "function"

# Tool parameter types
class ToolParamType(str, Enum):
    OBJECT = "object"
    STRING = "string"
    INTEGER = "integer"
    NUMBER = "number"
    BOOLEAN = "boolean"
    ARRAY = "array"
    NULL = "null"

class Role(str, Enum):
    GUEST = "guest"
    USER = "user"
    ADMIN = "admin"
    SYSTEM = "system"

